---
title: "Calculate dilution ratio"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, kableExtra)
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/', 
                        warning = FALSE, message = FALSE, cache = FALSE)
```

## load data

averaged data

```{r}
  samples <- readRDS("../../r_data/samples.RDS")  # sample info
  co2 <- readRDS("../../r_data/co2_merged_avg.RDS")
  fivegas <- readRDS("../../r_data/fivegas_dilution.RDS")
```

real-time data

```{r}
  co2_rt <- readRDS("../../r_data/co2_merged.RDS")
  fivegas_rt <- readRDS("../../r_data/fivegas_merged.RDS")
```

load schemes

```{r}
  qc_colors <- readRDS("../../r_data/qc_colors.RDS")
  lod_shapes <- readRDS("../../r_data/lod_shapes.RDS")
```

# plot co2 traces

```{r, fig.width=12, fig.height=30}
  fivegas_rt %>%
    dplyr::filter(pol == "co2") %>%
    dplyr::select(id, datetime, val, qc) %>%
    dplyr::mutate(loc = "fivegas") %>%
    dplyr::bind_rows(co2_rt %>%
                       dplyr::select(id, datetime, loc, val, qc)) %>%
    ggplot(aes(x = datetime, y = val, color = loc)) + 
      geom_point() +
      facet_wrap(~id, ncol = 4) +
      theme_bw() +
      theme(text = element_text(size = 12),
            legend.position = "top") +
      facet_wrap(~id, ncol = 4, scales = "free") +
      ylab("concentration (microgram per meter cubed)") +
      xlab("")
```

notes:

* 13A missing data - mark as bad

# calculate dilution ratio

combine data

```{r}
  dilution <-
    co2 %>%
    tidyr::spread("loc", "val") %>%
    dplyr::filter(qc == "ok") %>%
    dplyr::select(id, lab, sample) %>%
    dplyr::rename("dilution" = "sample") %>%
    dplyr::left_join(fivegas %>%
                       dplyr::select(id, val) %>%
                       dplyr::rename("sample" = "val"), by = "id") %>%
    dplyr::filter(id != "13A") %>%
    na.omit()
```

calculate dilution ratio

```{r}
  dilution <-
    dilution %>%
    dplyr::mutate(ratio = (dilution - lab) / (sample - lab))
```

# plot: dilution ratio

```{r}
  dilution %>%
    dplyr::left_join(dplyr::select(samples, id, date), by = "id") %>%
    ggplot(aes(x = date, y = ratio)) +
    geom_point(size = 2) +
    theme_bw() +
    xlab("") +
    ylab("dilution ratio")
```

