---
title: "Calculate emission factors"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse)
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

load data

```{r}
  samples <- readRDS("../../r_data/samples.RDS")
  fuel <- readRDS("../../r_data/fuel_burnt.RDS")
  emissions <- readRDS("../../r_data/emissions.RDS")
  fuel_properties <- readRDS("../../r_data/fuel_properties.RDS")
  energy <- readRDS("../../r_data/energy.RDS")
```

remove unused tests

```{r}
  emissions <-
    emissions %>%
    dplyr::filter(!is.na(val), !grepl("27|28|29|30", id))

  fuel <-
    fuel %>%
    dplyr::filter(!grepl("27|28|29|30", id))
```

# mass carbon per test

```{r}
  mass_carbon <-
    emissions %>%
    dplyr::filter(metric == "mass_carbon") %>%
    dplyr::group_by(id) %>%
    dplyr::filter(val >= 0) %>% 
    dplyr::summarise(mass_carbon = sum(val, na.rm = TRUE),
                     mass_carbon = mass_carbon  * 1e-6)
```

# carbon balance

calculate fuel burned using carbon balance method

```{r} 
  mass_fuel <-
    fuel %>%
    dplyr::left_join(dplyr::select(samples, id, fuel), by = "id") %>%
    dplyr::left_join(fuel_properties, by = "fuel") %>%
    dplyr::left_join(mass_carbon, by = "id") %>%
    dplyr::mutate(mass_fuel_c = mass_carbon * (1 / carbon_fraction))
```

# mass of fuel emissions factors

```{r, echo=TRUE} 
  fuel_mass_factors <- 
    emissions %>%
    dplyr::filter(metric == "mass_emitted") %>%
    dplyr::left_join(mass_fuel, by = "id") %>%
    dplyr::mutate(val =  (val * 1e-3) / (mass_fuel * 1e-3)) %>%
    dplyr::select(id, pol, pol_category, val, qc) %>%
    dplyr::mutate(units = "miligrams per kilograms fuel",
                  metric = "mass_fuel_ef")
```

# energy of fuel emissions factors

```{r, echo=TRUE} 
  fuel_energy_factors <- 
    emissions %>%
    dplyr::filter(metric == "mass_emitted") %>%
    dplyr::left_join(mass_fuel, by = "id") %>%
    dplyr::mutate(val =  ((val * 1e-3) / (mass_fuel * 1e-3)) * (1 / lhv)) %>%
    dplyr::select(id, pol, pol_category, val, qc) %>%
    dplyr::mutate(units = "miligrams per kilojoule fuel",
                  metric = "energy_fuel_ef")
```

# energy emissions factors

```{r}
  energy_factors <-
    emissions %>%
    dplyr::filter(metric == "mass_emitted") %>%
    dplyr::left_join(energy, by = "id") %>%
    dplyr::mutate(val =  (val * 1e-3) / (joules * 1e-6)) %>% 
    dplyr::select(id, pol, pol_category, val, qc) %>%
    dplyr::mutate(units = "miligrams per Megajoule delivered",
                  metric = "energy_delivered_ef")
```

```{r}
  emissions_factors <-
    fuel_mass_factors %>%
    dplyr::bind_rows(fuel_energy_factors) %>%
    dplyr::bind_rows(energy_factors)
```

# save

```{r}
  saveRDS(emissions_factors, file = "../../r_data/emissions_factors.RDS")
```

# Plots

## fuel burnt vs carbon

```{r, fig.width=10}  
  ggplot(mass_fuel, aes(x = mass_fuel, y = mass_fuel_c, color = fuel)) +
    geom_point() +
    theme_minimal() +
    xlab("mass of fuel (measured) [kg]") +
    ylab("mass of fuel (carbon balance) [kg]")
```

