---
title: "Combine all pollutant data and calculate additional emissions metrics"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, kableExtra)
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

## load files

```{r}
  emissions <- readRDS(file = "../../r_data/emissions_factors.RDS")
  samples <- readRDS(file = "../../r_data/samples.RDS")
```

## relevel samples

```{r, echo=FALSE}
  samples <-
    samples %>%
    dplyr::mutate(stove = 
                    stove %>% 
                    factor %>% 
                    forcats::fct_relevel("three-stone fire",
                                         "chulha",
                                         "rocket elbow",
                                         "built-in plancha",
                                         "fan rocket-elbow",
                                         "forced-draft gasifier",
                                         "ceramic charcoal",
                                         "metal charcoal",
                                         "wick kerosene",
                                         "pressure kerosene",
                                         "lpg") %>%
                    forcats::fct_recode("Three-stone fire" = "three-stone fire",
                                         "Mud chulha" = "chulha",
                                         "Rocket elbow" = "rocket elbow",
                                         "Built-in plancha" = "built-in plancha",
                                         "Fan rocket elbow" = "fan rocket-elbow",
                                         "Gasifier" = "forced-draft gasifier",
                                         "Ceramic jiko" = "ceramic charcoal",
                                          "Metal jiko" = "metal charcoal",
                                          "Wick kerosene" = "wick kerosene",
                                         "Pressure kerosene" = "pressure kerosene",
                                          "LPG" = "lpg"))
```

## add stove fuel info and select pollutants

```{r}
  emissions <-
    emissions %>%
    dplyr::left_join(samples %>%
                       dplyr::select(id, stove, fuel, stovecat, date, fuelcat), by = "id") %>%
    dplyr::filter(grepl("ions|^ec$|^om$|om_unc|ec_unc|pm_mass", pol_category)) %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

## filter out values below background

```{r}
  emissions <-
    emissions %>%
    dplyr::filter(bg != "below", !is.na(val))
```

# mass balance

```{r}
  ec_oc_ions <-
    emissions %>%
    dplyr::filter(!grepl("unc", pol_category)) %>%
    dplyr::group_by(id, pol_category, stove, fuel, fuelcat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE),
                     qc = first(qc)) %>%
    tidyr::spread(pol_category, val) %>%
    na.omit %>%
    tidyr::gather("pol", "val", 6:8) %>%
    dplyr::group_by(id, stove, fuel, fuelcat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE),
                     qc = first(qc)) %>%
    dplyr::rename("ec_oc_ions" = "val")
```

```{r}
  ec_oc_ions_unc <-
    emissions %>%
    dplyr::filter(grepl("unc", pol)) %>%
    dplyr::select(id, pol, val) %>%
    tidyr::spread(pol, val) %>%
    dplyr::mutate(unc = sqrt(ec_unc^2 + om_unc^2)) %>%
    dplyr::select(id, unc)
```

```{r}
  pm_mass <-
    emissions %>%
    dplyr::filter(grepl("pm_mass", pol_category)) %>%
    tidyr::spread(pol_category, val) %>%
    na.omit %>%
    dplyr::select(id, pm_mass) 
```

```{r}
  pm_comp <-
    ec_oc_ions %>%
    dplyr::left_join(pm_mass, by = "id") %>%
    dplyr::left_join(ec_oc_ions_unc, by = "id")
```

```{r}
  mod = lm(ec_oc_ions ~ pm_mass, data = pm_comp)
  summary(mod)
  sqrt(mean(mod$residuals^2))
```

```{r mass_balance, echo=FALSE, fig.width=7, fig.height=5}
  pm_comp %>%
    ggplot(aes(y = ec_oc_ions, x = pm_mass)) +
      geom_point(aes(color = stove), size = 2) +
      geom_errorbar(aes(ymin = ec_oc_ions - unc, ymax = ec_oc_ions + unc, color = stove)) +
      geom_abline(slope = 1, intercept = 0) +
      geom_smooth(method="lm",se=FALSE) +
      scale_y_log10(limits = c(0.1, 1000), breaks = c(0.1, 1, 10, 100, 1000)) +
      scale_x_log10(limits = c(0.1, 1000), breaks = c(0.1, 1, 10, 100, 1000)) +
      theme_bw() +
      theme(text = element_text(size = 14),
            legend.position = "right",
            legend.title = element_blank()) +
      xlab(expression(paste(PM[2.5], " EF (mg/", MJ[delivered], ")"))) +
      ylab(expression(paste("EC + OA + inorganic ions", " EF (mg/", MJ[delivered], ")")))
```