---
title: "Emission Factor Summary"
author: "Jessica Tryner"
date: "December 16, 2018"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
```

# Load

* sample info

```{r}
  samples <- readRDS("../r_files/samples.RDS")
```

* Emissions data

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  data_energy    <- readRDS("../r_files/ef_energy.RDS")
  data_fuel      <- readRDS("../r_files/ef_fuel.RDS")
  data_emissions <- readRDS("../r_files/emissions_long.RDS")
```

# Clean data

### Test metadata

```{r}
  df_samples <- dplyr::select(samples,
                              id, date, stove, fuel, type, mc_level, mc_dry) %>%
                dplyr::filter(type != "bg",
                              id   != "FH2") %>%
                dplyr::mutate(type = ifelse(type=="lab", "milled", "split"))
```

### Mass per unit energy delivered

Grams of pollutant per megajoule of energy delivered to the cooking surface.

```{r}
  df_ef_energy <- dplyr::select(data_energy,
                                id, pol, g_pol_mjd) %>%
                  dplyr::mutate(metric = "g_MJd") %>%
                  plyr::rename(c("g_pol_mjd"="value"))
```

### Mass per mass of fuel burned

Grams of pollutant per kilogram of fuel burned. 

```{r}
  df_ef_fuel <- dplyr::select(data_fuel,
                              id, pol, g_pol_kg_fuel) %>%
                dplyr::mutate(metric = "g_pol_kg_fuel") %>%
                plyr::rename(c("g_pol_kg_fuel"="value"))           
```

### Mass of carbon emitted

```{r}
  df_emissions <- dplyr::filter(data_emissions, metric=="mass_carbon",
                                                substr(id,1,2) != "BG",
                                                substr(id,1,1) != "G",
                                                id != "FH2") %>%
                  dplyr::select(-inst) %>%
                  dplyr::mutate(metric = "g_carbon",
                                id     = as.factor(id))
```

# Combine data

```{r}
  df_summary <- dplyr::bind_rows(df_ef_energy, df_ef_fuel) %>%
                plyr::rename(c("pol"="pollutant")) %>%
                dplyr::filter(pollutant %in% c("co2","co","ch4","grav","ec","oc",
                                 "acetaldehyde",     "acetone",          "acrolein",
                                 "benzaldehyde",     "butanone",         "butyraldehyde",
                                 "crotonaldehyde",   "formaldehyde",     "hexaldehyde",
                                 "isovaleraldehyde", "m_p_tolualdehyde", "methacrolein",
                                 "o_tolualdehyde",   "propionaldehyde",  "valeraldehyde",
                                 "benzene",          "toluene",          "ethylbenzene",
                                 "m+p-xylene",       "o-xylene")) %>%
                dplyr::mutate(pollutant = ifelse(pollutant=="grav", "pm2_5", pollutant))

  df_summary <- dplyr::left_join(df_samples, df_summary, by=c("id")) %>%
                plyr::rename(c("id"     = "test_id",
                               "type"   = "fuel_type",
                               "mc_dry" = "fuel_mc_dry"))            %>%
                dplyr::mutate(mc_level = as.factor(mc_level))
  
  levels(df_summary$mc_level) <- c("low","medium","high")
  
  df_summary <- dplyr::arrange(df_summary, metric, pollutant, mc_level, fuel_type)
```

# Save

```{r}
  saveRDS(df_summary, file = "../r_files/ef_summary.RDS")
  write_csv(df_summary, "../r_files/ef_summary.csv", na="NA", append=FALSE)
```



