---
title: "Emissions"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
  library(knitr)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  source("../r_scripts/R_functions.R")
```

# Load

* constants

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  load("../r_files/calc_constants.Rda")
```

* metadata

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  load("../r_files/samples.Rda")
  load("../r_files/test_times.Rda")
  load("../r_files/batch_wgts.Rda")
  load("../r_files/wood_wgts.Rda")
```

# Timestamps

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  times <- dplyr::filter(test_times, var == "start_1" | var == "shutdown") %>%
           tidyr::spread(var, value) %>%
           dplyr::select(-date) %>%
           dplyr::rename(start = start_1, end = shutdown)
```

# Fuel

## batch stoves

* fuel consumed

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  batch_mass <- dplyr::filter(batch_wgts, var == "fuel" |
                                          var == "refueled" |
                                          var == "preshutdown") %>%
                tidyr::spread(var, value) %>%
                dplyr::rename(wgt_fuel = fuel,
                              wgt_refuel = refueled,
                              wgt_shutdown = preshutdown) %>%
                dplyr::mutate(mass_fuel = wgt_fuel + wgt_refuel - wgt_shutdown)
```

## wood stoves

* fuel consumed

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  wood_mass <- dplyr::filter(wood_wgts, var == "fuel" |
                                        var == "ashpot_unusedfuel" |
                                        var == "ashpot_char_ash" |
                                        var == "ashpot_lid") %>%
                tidyr::spread(var, value) %>%
                dplyr::rename(wgt_fuel = fuel,
                              wgt_pot_unusedfuel = ashpot_unusedfuel,
                              wgt_pot_char_ash = ashpot_char_ash,
                              wgt_pot = ashpot_lid) %>%
                dplyr::mutate(mass_fuel = wgt_fuel -
                                          wgt_pot_unusedfuel -
                                          wgt_pot_char_ash +
                                          2 * wgt_pot)
```

## merge

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  fuel_burnt <- dplyr::bind_rows(dplyr::select(batch_mass, id, mass_fuel),
                                 dplyr::select(wood_mass, id, mass_fuel)) %>%
                dplyr::mutate(id = as.factor(id)) %>%
                dplyr::filter(grepl("^[0-9]", id) == TRUE)
```

# Plot

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=8}
  p_data <- dplyr::left_join(samples, fuel_burnt) %>%
            dplyr::mutate(id = as.factor(id)) %>%
            dplyr::filter(grepl("^[0-9]", id) == TRUE)

  ggplot(p_data, aes(x = id, y = mass_fuel, colour = stove)) +
        geom_point() +
        theme_minimal() + 
        theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
        theme(legend.position = "top") +
        ylab("fuel burnt (g)")
```

## save fuel file

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  save(fuel_burnt, file = "../r_files/fuel_burnt.Rda")
```

___

