---
title: "Emission Factor Summary Tables"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r global_options, include=FALSE}
  library(tidyverse)
  library(forcats)
```

# Load and tidy data

* Load data and meta data

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  load("../r_files/emission_factors.Rda")
  load("../r_files/samples.Rda")
```

* Load functions

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  source("../r_scripts/R_functions.R")
```

* Output emissions factors column names 

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  colnames(emission_factors)
```

* Add stove/fuel information

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors <- dplyr::left_join(emission_factors, 
                                       dplyr::select(samples, id, stove, fuel,
                                                              fuelcat, stovecat),
                                       by = "id")
```

* Use carbon balance method for missing emissions factors

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors <- dplyr::mutate(emission_factors, 
                                    mass_ef_comb = 
                                      ifelse(is.na(mass_ef),
                                             mass_c_ef, mass_ef)) %>%
                      dplyr::mutate(energy_ef_comb =
                                      ifelse(is.na(energy_ef), energy_c_ef,
                                             energy_ef))
```

* Remove outliers

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors <- dplyr::filter(emission_factors, mass_ef_comb > 0) %>%
                      dplyr::filter(energy_ef_comb > 0) 
```

# Plot summary tables

## Replicate overview

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width = 35,  fig.height = 10}
  replicates <- dplyr::distinct(emission_factors) %>%
                dplyr::filter(grepl("ecoc|grav",inst)) %>%
                dplyr::group_by_(.dots = c("pol", "stove", "fuel", "fuelcat")) %>% 
                dplyr::count() %>%
                tidyr::spread(pol, n) %>%
                dplyr::mutate(n = ifelse(is.na(n), 0, n)) %>%
                tidyr::gather(po1, n) %>%
                dplyr::mutate(stove_fuel = paste(stove, ":", fuel))

  ggplot(data = replicates, aes(stove_fuel, pol, fill = n, label = n))+
       geom_tile(color = "white") +
       geom_text(color = "black", size = 7) +
       scale_fill_gradient2(low = "white", high = "purple",
                            midpoint = 0, limit = c(0, max(replicates$n)), space = "Lab", 
                            name = "Number of replicates") +
       facet_grid(~ fuelcat, scales = "free", space = "free") +
       theme_bw() + 
       theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 18, hjust = 1),
             axis.text.y = element_text(size = 18),
             axis.title.x = element_blank(),
             axis.title.y = element_blank(),
             panel.grid.major = element_blank(),
             panel.border = element_blank(),
             panel.background = element_blank(),
             axis.ticks = element_blank(),
             legend.position = "top",
             legend.direction = "horizontal", 
             legend.title = element_text(size = 22),
             legend.text = element_text(size = 20),
             strip.text.x = element_text(size = 20)) +
             scale_x_discrete(label=function(x) sub(" [: : :]", "\n", x)) +
       guides(fill = guide_colorbar(barwidth = 10, barheight = 2,
                                    title.position = "top", title.hjust = 0.5)) +
       coord_fixed()

```






