---
title: "Energy applied"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
  library(knitr)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  source("../r_scripts/R_functions.R")
```

# Load

* water (pot) temperature and emissions

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emissions_long <- readRDS("../r_files/emissions_long.RDS")
  temp_merged <- readRDS("../r_files/temp_merged.RDS")
  mean_mc <- readRDS("../r_files/mean_mc_df.RDS")
  fuel_burnt <- readRDS("../r_files/fuel_burnt.RDS")
```

* constants

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}

  c_water <- readRDS("../r_files/c_water.RDS")
  
  hfg_water <- readRDS("../r_files/hfg_water.RDS")
```

* metadata

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  samples <- readRDS("../r_files/samples.RDS")
  test_times <- readRDS("../r_files/test_times.RDS")
  mc_test_log <- readRDS("../r_files/mc_test_log.RDS")

```

# Test timestamps

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  times <- dplyr::filter(test_times, var == "set_1" | var == "end") %>%
           tidyr::spread(var, value) %>%
           dplyr::rename(start = set_1) %>%
           dplyr::filter(!grepl("^BG", id))
```

# Energy

## joules applied


* pot mass

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
pot_weights <- select(mc_test_log, wgt_pot_a, wgt_on_1, wgt_off_1, id, date) %>%
               mutate(delta_m = wgt_on_1 - wgt_off_1, m_start = wgt_on_1 - wgt_pot_a) %>%
               filter(!is.na(wgt_on_1))
  

```

* extract temperature for periods of interest

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  temp_merged <- mutate(temp_merged, time = time + 3600)  

  e_temp <- dplyr::filter(temp_merged, grepl("stove", loc))


  e_temp <- filter_temp(times, e_temp)
```

* temperature change

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}

t_range <- dplyr::group_by(e_temp, id) %>%
            dplyr::summarise(t_min = min(t_oc, na.rm = TRUE),  
                             t_max = max(t_oc, na.rm = TRUE),
                             t_med = median(t_oc),
                             t_high_avg = t_med + 0.5*(t_max - t_med))

t_per_kg <- left_join(t_range, fuel_burnt, by = "id") %>%
            left_join(mean_mc) %>%
            mutate(kg_per_degree = mass_burned_correct/(t_max - t_min))

ggplot(t_per_kg, aes(x = mean_mc, y = kg_per_degree)) +
  geom_point() +
  theme_bw()

#saveRDS(t_range, file = "../r_files/t_range.RDS")
```

```{r}
# plot temps
e_temp1 <- dplyr::filter(temp_merged, grepl("pot", loc))  
e_temp1 <- filter_temp(times, e_temp1)
 
t_range1 <- dplyr::filter(e_temp1, !grepl("FH2", id)) %>%
            group_by(id) %>%
            dplyr::summarise(t_min = min(t_oc, na.rm = TRUE),  
                             t_max = max(t_oc, na.rm = TRUE),
                             t_med = median(t_oc),
                             t_mean = mean(t_oc),
                             t_high_avg = t_med + 0.5*(t_max - t_med))

t_means1 <- left_join(t_range1, dplyr::select(samples, id, type, mc_level), by = "id") %>%
            group_by(mc_level) %>%
            summarise(mean = mean(t_mean))

mean_mc <- readRDS("../r_files/mean_mc_df.RDS")

 temp_plot1 <- left_join(t_range1, mean_mc, by = "id")
 
 cols <- c("Max" = "#FF3366", "Mean" = "#FF9900", "Min" = "#330099")
 
temp_fig <- ggplot() +
   scale_color_manual(name = "Temperature", values = cols) +
   geom_point(data = temp_plot1, aes(x = mean_mc, y = t_max, color = "Max")) +
   geom_point(data = temp_plot1, aes(x = mean_mc, y = t_mean, color = "Mean")) +
   #geom_point(data = temp_plot1, aes(x = mean_mc, y = t_med, color = "Median")) +
   geom_point(data = temp_plot1, aes(x = mean_mc, y = t_min, color = "Min")) +
   #geom_point(aes(y = t_min, color= "blue")) +
   theme_bw() +
   labs(x = "Mean Moisture Content (%)", y = "Temperature (C)")

ggsave(filename = "temp_fig.svg", plot = temp_fig, device = "svg", width = 7, height = 6, units = "in")
```


* merge data

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  e_data <- dplyr::left_join(pot_weights, times, by = "id") %>%
            dplyr::left_join(t_range, by = "id")%>%
            dplyr::select(-date.y) %>%
            dplyr::rename(date = date.x)
```

* energy applied

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  e_data <- dplyr::mutate(e_data,
                          mass_evap = delta_m,
                          mass_h2o = wgt_on_1 - wgt_pot_a,
                          dt = t_max - t_min,
                          j_heat = mass_h2o * c_water * dt, # g * J/(g.oC) * oC
                          j_vap = mass_evap * hfg_water,
                          joules = j_heat + j_vap)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, eval = FALSE}
  kable(dplyr::slice(e_data, 1:5),
        align = 'c', caption = "Energy Numbers")
```

* energy applied per test

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  energy <- dplyr::select(e_data, id, joules) %>%
            dplyr::group_by(id) %>%
            dplyr::summarise(joules = sum(joules, na.rm = TRUE))
```

# Plots

## temperature (id & loc)

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=50}
  ggplot(dplyr::filter(e_temp, loc != "flue"),
         aes(datetime, t_oc, color = loc)) +
         geom_line() +
         geom_point() +
         facet_wrap(~id, ncol = 3, scales = "free") +
         theme_minimal() +
         theme(legend.position = "top") +
         ylab("degress celsius") +
         theme(legend.position = "top")
```

## temperature (id & rep)




# Plot EFs for Energy

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
 ef_energy <- dplyr::left_join(dplyr::filter(emissions_long, metric == "mass_emitted", !grepl("^BG|G", id)), 
                                       energy,
                                       by = "id" ) %>%
                      dplyr::mutate(mass_pol_energy = ((value * 1e-6) / (joules *1e-6))) %>%
              left_join(mean_mc, by = "id")
```

## energy delivered


```{r}
p_data <- dplyr::left_join(ef_energy,
                             dplyr::select(samples, id, type, mc_level),
                                           by = "id") %>%
            dplyr::filter(type != "bg") %>%
            dplyr::mutate(mc_level = forcats::fct_relevel(mc_level, "low",
                                                                    "med",
                                                                    "high")) %>%
            dplyr::mutate(id = factor(id, levels = c("FL1", "FL2", "FL3", "FL4", "FM1", "FM2",
                                                     "FM3", "FM4", "FH1", "FH2", "FH3", "FH4",
                                                     "LL1", "LL2", "LL3", "LL4", "LM1", "LM2",
                                                     "LM3", "LM4", "LH1", "LH2", "LH3",
                                                     "LH4")))
mj_delivered <- p_data %>%
                select(joules, id, type, mc_level, mean_mc) %>%
                mutate(joules = joules * 10^-6) %>%
                distinct()

mj_per_sec <- left_join(mj_delivered, times, by = "id") %>%
              mutate(MW = joules/(end-start))

ggplot(mj_per_sec, aes(x = mean_mc, y = MW)) +
  geom_point() +
  theme_bw()

ggplot(mj_delivered, aes(x = mean_mc, y = joules, color = mc_level)) +
  geom_point(size = 3.5)
```

```{r}
temps <- group_by(e_temp, id) %>%
            dplyr::summarise(t_mean = mean(t_oc, na.rm = TRUE))

grav_energy <- p_data %>%
          dplyr::filter(pol %in% "grav") %>%
          dplyr::select(-inst) %>%
          left_join(temps, by = "id")

grav_fig_energy <- ggplot(grav_energy, aes(x = mean_mc, y = mass_pol_energy, color = mc_level, shape = type)) +
  geom_point(size = 3.5) +
  theme_bw() +
  theme(text = element_text(size=15)) +
  ylab("EF [g pol / MJ Delivered]") + xlab("Moisture Content (%)") +
  #facet_wrap(~pol, scales = "free") +
  scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(color = "MC Level", shape = "Fuel Shape")

ggsave(filename = "grav_fig_energy.svg", plot = grav_fig_energy, device = "svg", width = 7, height = 6, units = "in")
```

```{r}

gas_energy <- p_data %>%
          dplyr::filter(pol %in% c("co", "co2", "ch4")) %>%
          dplyr::select(-inst) %>%
          left_join(temps, by = "id")

ggplot(gas_energy, aes(x = mean_mc, y = mass_pol_energy, color = mc_level, shape = type)) +
  geom_point(size = 3.5) +
  theme_bw() +
  theme(text = element_text(size=15)) +
  ylab("EF [g pol / MJ Delivered]") + xlab("Moisture Content (%)") +
  facet_wrap(~pol, scales = "free", ncol = 2) +
  scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(color = "MC Level", shape = "Fuel Shape")
```

```{r fig.height=6}

voc_energy <- p_data %>%
          dplyr::filter(pol %in% c("benzene", "toluene", "ethylbenzene",
                                   "m+p-xylene", "o-xylene")) %>%
          dplyr::select(-inst) %>%
          left_join(temps, by = "id") %>%
          mutate(pol = as.factor(pol)) %>%
          mutate(pol = forcats::fct_relevel(pol, "benzene",
                                                      "toluene",
                                                      "ethylbenzene",
                                                      "m+p-xylene",
                                                      "o-xylene")) %>%
          rename(`MC Level` = mc_level, `Fuel Shape` = type)

voc_fig_energy <- ggplot(voc_energy, aes(x = mean_mc, y = mass_pol_energy*1000, color = `MC Level`, shape = `Fuel Shape`)) +
  geom_point(size = 3.5) +
  theme_bw() +
  theme(text = element_text(size=15)) +
  ylab("EF [mg pol / MJ Delivered]") + xlab("Moisture Content (%)") +
  facet_wrap(~pol, scales = "free", ncol = 2) +
  scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(color = "MC Level", shape = "Fuel Shape")

ggsave(filename = "voc_fig_energy.svg", plot = voc_fig_energy, device = "svg", width = 7, height = 6, units = "in")
```

```{r}

carbonyl_energy <- p_data %>%
          dplyr::filter(pol %in% c("formaldehyde", "acetaldehyde")) %>%
          dplyr::select(-inst) %>%
          left_join(temps, by = "id")

ggplot(carbonyl_energy, aes(x = mean_mc, y = mass_pol_energy, color = mc_level, shape = type)) +
  geom_point(size = 3.5) +
  theme_bw() +
  theme(text = element_text(size=15)) +
  ylab("EF [g pol / MJ Delivered]") + xlab("Moisture Content (%)") +
  facet_wrap(~pol, scales = "free", ncol = 2) +
  scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(color = "MC Level", shape = "Fuel Shape")
```

```{r}

ecoc_energy <- p_data %>%
          dplyr::filter(pol %in% c("ec", "oc")) %>%
          dplyr::select(-inst) %>%
          left_join(temps, by = "id")

ggplot(ecoc_energy, aes(x = mean_mc, y = mass_pol_energy, color = mc_level, shape = type)) +
  geom_point(size = 3.5) +
  theme_bw() +
  theme(text = element_text(size=15)) +
  ylab("EF [g pol / MJ Delivered]") + xlab("Moisture Content (%)") +
  facet_wrap(~pol, scales = "free", ncol = 2) +
  scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(color = "MC Level", shape = "Fuel Shape")
```

```{r}

ecoc_grav_energy <- p_data %>%
          dplyr::filter(pol %in% c("grav", "ec", "oc")) %>%
          dplyr::select(-inst) %>%
          left_join(temps, by = "id") %>%
          mutate(pol = ifelse(pol == "grav", "PM2.5", pol))

ecoc_grav_fig <- ggplot(ecoc_grav_energy, aes(x = mean_mc, y = mass_pol_energy, color = mc_level, shape = type)) +
  geom_point(size = 3.5) +
  theme_bw() +
  theme(text = element_text(size=15)) +
  ylab("EF [g pol / MJ Delivered]") + xlab("Moisture Content (%)") +
  facet_wrap(~pol, scales = "free", ncol = 2) +
  scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(color = "MC Level", shape = "Fuel Shape")

ggsave(filename = "ecoc_grav_fig.svg", plot = ecoc_grav_fig, device = "svg", width = 7, height = 5, units = "in")
```

# all pollutants one figure
```{r fig.height=4, fig.width=9}
all_energy <- p_data %>%
          dplyr::filter(pol %in% c("grav", "ec", "oc", "formaldehyde", "acetaldehyde",
                                   "benzene", "co", "ch4")) %>%
          dplyr::select(-inst) %>%
          left_join(temps, by = "id") %>%
          mutate(pol = as.factor(pol)) %>%
          mutate(pol = factor(pol,
                levels = c("co", "grav","ec", "oc", "ch4",
                           "formaldehyde", "acetaldehyde", "benzene"))) %>%
          mutate(type = ifelse(type %in% "lab", "Milled", "Split"),
                 mc_level = ifelse(mc_level %in% "med", "medium",
                                   ifelse(mc_level %in% "high", "high", "low"))) %>%
          mutate(mc_level = factor(mc_level, levels = c("low", "medium", "high"))) %>%
          mutate(mass_pol_energy_mg = mass_pol_energy *1000) %>%
          mutate(panel = as.factor(ifelse(pol %in% c("grav", "ec", "oc"), "Particulate Matter", "Gases")))

# graphical display volckens would like to see

cols2 <- c("PM2.5/10" = "#FF3366", "Elemental Carbon/2" = "#FF9900", "Organic Carbon/10" = "#33CC99",
          "Carbon Monoxide/100" = "#FF6633", "Methane/10" = "#330099", "Benzene" = "#CC0066",
          "Acetaldehyde" = "#339999", "Formaldehyde/10" = "#0099CC")

ggplot(data = all_energy) +
  scale_colour_manual(name = "Pollutant", values = cols2) +
  geom_point(data = filter(all_energy, pol %in% "grav"), aes(x = mean_mc, y = mass_pol_energy_mg/10,
                           shape = type, color = "PM2.5/10"), size = 2, alpha = 0.8) +
  geom_point(data = filter(all_energy, pol %in% "ec"), aes(x = mean_mc, y = mass_pol_energy_mg/2,
                           shape = type, color = "Elemental Carbon/2"), size = 2, alpha = 0.8) +
  geom_point(data = filter(all_energy, pol %in% "oc"), aes(x = mean_mc, y = mass_pol_energy_mg/10,
                           shape = type, color = "Organic Carbon/10"), size = 2, alpha = 0.8) +
  geom_point(data = filter(all_energy, pol %in% "co"), aes(x = mean_mc, y = mass_pol_energy_mg/100,
                           shape = type, color = "Carbon Monoxide/100"), size = 2, alpha = 0.8) +
  geom_point(data = filter(all_energy, pol %in% "ch4"), aes(x = mean_mc, y = mass_pol_energy_mg/10,
                           shape = type, color = "Methane/10"), size = 2, alpha = 0.8) +
  geom_point(data = filter(all_energy, pol %in% "benzene"), aes(x = mean_mc, y = mass_pol_energy_mg,
                           shape = type, color = "Benzene"), size = 2, alpha = 0.8) +
  geom_point(data = filter(all_energy, pol %in% "acetaldehyde"), aes(x = mean_mc, y = mass_pol_energy_mg,
                           shape = type, color = "Acetaldehyde"), size = 2, alpha = 0.8) +
  geom_point(data = filter(all_energy, pol %in% "formaldehyde"), aes(x = mean_mc, y = mass_pol_energy_mg/10,
                           shape = type, color = "Formaldehyde/10"), size = 2, alpha = 0.8) +
  facet_wrap(~panel, ncol = 2, scales = "free_y") +
  theme_bw() +
  theme(text = element_text(size=12), legend.position = "right") +
  #strip.background = element_blank(),
  #strip.text.x = element_blank()) +
  ylab("EF [mg / MJ Delivered]") + xlab("Moisture Content (%)") +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(shape = "Fuel Shape")

# graphical display I like
ggplot(all_energy, aes(x = mean_mc, y = mass_pol_energy_mg, shape = type)) +
  theme_bw() +
  theme(text = element_text(size=12), legend.position = "top",
  strip.background = element_blank(),
  strip.text.x = element_blank()) +
  ylab("EF [mg / MJ Delivered]") + xlab("Moisture Content (%)") +
  #scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(color = "MC Level", shape = "Fuel Shape") +
  geom_hline(aes(yintercept = 1030), size = 1, data=subset(all_energy, pol == "grav"), color = "#FF3366") +
  geom_hline(aes(yintercept = 481), size = 1,data=subset(all_energy, pol == "grav"), color = "#FF9900") +
  geom_hline(aes(yintercept = 218), size = 1,data=subset(all_energy, pol == "grav"), color = "#33CC99") +
  geom_hline(aes(yintercept = 62), size = 1,data=subset(all_energy, pol == "grav"), color = "#339999") +
  geom_hline(aes(yintercept = 5), size = 1,data=subset(all_energy, pol == "grav"), color = "#330099") +
  geom_hline(aes(yintercept = 18300), size = 1,data=subset(all_energy, pol == "co"), color = "#FF3366") +
  geom_hline(aes(yintercept = 11500), size = 1,data=subset(all_energy, pol == "co"), color = "#FF9900") +
  geom_hline(aes(yintercept = 7200), size = 1,data=subset(all_energy, pol == "co"), color = "#33CC99") +
  geom_hline(aes(yintercept = 4400), size = 1,data=subset(all_energy, pol == "co"), color = "#339999") +
  geom_hline(aes(yintercept = 3000), size = 1,data=subset(all_energy, pol == "co"), color = "#330099") +
  facet_wrap(~pol, ncol = 4, scales = "free_y") + #dummy value for now to fix panel issue
  geom_text(aes(label = "CO", x = 7.5, y = 14000), colour = "black", data=subset(all_energy, pol == "co")) +
  geom_text(aes(label = "PM2.5", x = 9, y = 900), colour = "black", data=subset(all_energy, pol == "grav")) +
  geom_text(aes(label = "EC", x = 8, y = 40), colour = "black", data=subset(all_energy, pol == "ec")) +
  geom_text(aes(label = "OC", x = 25, y = 130), colour = "black", data=subset(all_energy, pol == "oc")) +
  geom_text(aes(label = "CH4", x = 25, y = 400), colour = "black", data=subset(all_energy, pol == "ch4")) +
  geom_text(aes(label = "CH2O", x = 25, y = 45), colour = "black", data=subset(all_energy, pol == "formaldehyde")) +
  geom_text(aes(label = "C2H4O", x = 25, y = 15), colour = "black", data=subset(all_energy, pol == "acetaldehyde")) +
  geom_text(aes(label = "C6H6", x = 25, y = 5), colour = "black", data=subset(all_energy, pol == "benzene")) +
  geom_point(size = 2, color = "black", alpha = 0.7)
```

```{r}
# final display for manuscript
main_energy <- ggplot(all_energy, aes(x = mean_mc, y = mass_pol_energy_mg, shape = type)) +
  theme_bw() +
  theme(text = element_text(size=12), legend.position = "none",
  strip.background = element_blank(),
  strip.text.x = element_blank()) +
  ylab("EF [mg / MJ Delivered]") + xlab("Moisture Content (%)") +
  #scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  scale_x_continuous(breaks = c(5, 15, 25)) +
  labs(color = "MC Level", shape = "Fuel Shape") +
  geom_point(size = 2, aes(color = pol), alpha = 0.7) +
  facet_wrap(~pol, ncol = 4, scales = "free_y") + #dummy value for now to fix panel issue
  scale_color_manual(values = c("#FF3366", "#FF9900", "#33CC99", "#339999", "#330099", "#CC0066", "#FF6633", "#0099CC")) +
  geom_hline(aes(yintercept = 1030), size = .5, data=subset(all_energy, pol == "grav"), color = "black") +
  geom_hline(aes(yintercept = 481), size = .5,data=subset(all_energy, pol == "grav"), color = "black") +
  geom_hline(aes(yintercept = 218), size = .5,data=subset(all_energy, pol == "grav"), color = "black") +
  geom_hline(aes(yintercept = 62), size = .5,data=subset(all_energy, pol == "grav"), color = "black") +
  geom_hline(aes(yintercept = 5), size = .5,data=subset(all_energy, pol == "grav"), color = "black") +
  geom_hline(aes(yintercept = 18300), size = .5,data=subset(all_energy, pol == "co"), color = "black") +
  geom_hline(aes(yintercept = 11500), size = .5,data=subset(all_energy, pol == "co"), color = "black") +
  geom_hline(aes(yintercept = 7200), size = .5,data=subset(all_energy, pol == "co"), color = "black") +
  geom_hline(aes(yintercept = 4400), size = .5,data=subset(all_energy, pol == "co"), color = "black") +
  geom_hline(aes(yintercept = 3000), size = .5,data=subset(all_energy, pol == "co"), color = "black") +
  geom_text(aes(label = "CO", x = 7.5, y = 14000), colour = "black", data=subset(all_energy, pol == "co")) +
  geom_text(aes(label = "PM2.5", x = 9, y = 900), colour = "black", data=subset(all_energy, pol == "grav")) +
  geom_text(aes(label = "EC", x = 8, y = 40), colour = "black", data=subset(all_energy, pol == "ec")) +
  geom_text(aes(label = "OC", x = 25, y = 130), colour = "black", data=subset(all_energy, pol == "oc")) +
  geom_text(aes(label = "CH4", x = 25, y = 400), colour = "black", data=subset(all_energy, pol == "ch4")) +
  geom_text(aes(label = "Formaldehyde", x = 20, y = 45), colour = "black", data=subset(all_energy, pol == "formaldehyde")) +
  geom_text(aes(label = "Acetaldehyde", x = 20, y = 15), colour = "black", data=subset(all_energy, pol == "acetaldehyde")) +
  geom_text(aes(label = "Benzene", x = 20, y = 5), colour = "black", data=subset(all_energy, pol == "benzene"))
  
ggsave(filename = "main_fig.pdf", plot = main_energy, width = 7, height = 3.5, units = "in")
ggsave(filename = "main_fig.svg", plot = main_energy, device = "svg", width = 7, height = 3.5, units = "in")
```

```{r fig.height= 11, fig.width=6}
carb_plot_energy <- filter(p_data, !grepl("ec|oc|co2|co|ch4|benzene|toluene|ethylbenzene|o-xylene|m+p-xylene|tc|grav|2_5_dimethylbenzaldehyde", pol)) %>%
  mutate(mass_pol_energy_mg = mass_pol_energy *1000) %>%
  rename(`MC Level` = mc_level, `Fuel Shape` = type)
             #rename(dimethylbenzaldehyde = `)

carb_energy <- ggplot(carb_plot_energy, aes(x = mean_mc, y = mass_pol_energy_mg, color = `MC Level`, shape = `Fuel Shape`)) +
  geom_point(size = 2) +
  theme_bw() +
  scale_color_manual(values = c("darkorange", "darkorchid3", "blue")) +
  theme(text = element_text(size = 12)) + 
  ylab("EF [mg pol / MJ Delivered]") + xlab("Moisture Content (%)") +
  facet_wrap(~pol, scales = "free_y", ncol = 3) +
  scale_x_discrete(labels = c("5", "15", "25"))

ggsave(filename = "carb_energy.pdf", plot = carb_energy)
ggsave(filename = "carb_fig_energy.svg", plot = carb_energy, device = "svg", width = 8, height = 10, units = "in")

```


```{r}
# anova tests for pollutants efs               
df_anova <- dplyr::select(all_energy, mass_pol_energy, type, mc_level, pol, id) %>%
       dplyr::mutate(type = as.factor(type),
                     mc_level = as.factor(mc_level)) %>%
       dplyr::filter(pol == "benzene") %>%
       dplyr::mutate(test_fuel_type = paste(type, mc_level, sep = "_"))
                
#TukeyHSD(aov(mass_pol_mass_fuel ~ test_fuel_type, df_anova))
#TukeyHSD(aov(mass_pol_mass_fuel ~ mc_level, df_anova))
pairwise.t.test(df_anova$mass_pol_energy, df_anova$test_fuel_type, p.adj = "none")
pairwise.t.test(df_anova$mass_pol_energy, df_anova$test_fuel_type, p.adj = "holm")
pairwise.t.test(df_anova$mass_pol_energy, df_anova$mc_level, p.adj = "none")
pairwise.t.test(df_anova$mass_pol_energy, df_anova$mc_level, p.adj = "holm")
```

```{r}
energy_means <- group_by(all_energy, mc_level, pol) %>%
       summarise(mean_ef = mean(mass_pol_energy), sd_ef = sd(mass_pol_energy))
```

