---
title: "Startup Emissions Analysis - g pol / startup event "
author: "Kristen Fedak"
date: "July 27, 2017"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: 
      collapsed: false
    theme: yeti
---

# Setup 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

  library(tidyverse)
  library(knitr)

```

# Load and format data
```{r}
  emission_factors <- readRDS(file = "../r_files/emission_factors.RDS")
```

```{r}
 source("../r_scripts/R_functions.R")
```

```{r include = FALSE}
# set variable types from character -> factor
# filter out bad QC data
# set fuel type order by survey result "commonality" of use. 
# create variable mass (g) pollutant emitted per startup event
# create variable average mass (g) of startup material per startup event
# filter out backgrounds and blanks
  ef_su_event <- dplyr::mutate(emission_factors, fuel = factor(fuel),
                                              qc = factor(qc),
                                              pol = factor(pol)) %>%
               dplyr::filter(qc != "bad") %>%
               dplyr::mutate(fuel = forcats::fct_relevel(fuel, "background", "kerosene",
                                                      "plastic_bags", "newspaper",
                                                      "leaves_twigs", "rubber",
                                                      "flipflops", "t_shirts",
                                                      "food_packaging", "wood_shims")) %>%
              dplyr::mutate(masspol_per_startup = (value * 1e-3) / fuel_quant, 
                            #value = ug emitted per test, so *1e-6 to convert to g for unit = mg per event 
                            mass_avg_startup = fuelmass_total / fuel_quant) %>% 
                            #fuelmass = g, so unit = g per startup bundle
              dplyr::filter(!grepl('31|32|33|34|35|36|37|38|39|40|41|42|43', id))
```

# Summary Tables

## Average mass of material burned per startup event
* unit = grams of material 
```{r}
fuel_sum <- dplyr::filter(ef_su_event, pol == 'grav') %>% 
            dplyr::group_by(fuel) %>%
            dplyr::summarize(n_tests = n(),
                             n_events_pertest = round(mean(fuel_quant), 2),
                             mean_fuelmass_perevent_g = round(mean(mass_avg_startup), 3))

knitr::kable(fuel_sum)
```

## Emissions Per startup Event
```{r}
  ef_sum <- ef_su_event %>% dplyr::group_by(fuel, pol) %>%
                            dplyr::summarize(nreps = n(),
                                     mean_ef = round(mean(masspol_per_startup, na.rm = TRUE), 3),
                                     min_ef = round(min(masspol_per_startup, na.rm = TRUE), 3),
                                     max_ef = round(max(masspol_per_startup, na.rm = TRUE), 3))
#mass_ef in units g pol / startup event; one average value per fuel_type.

ef_mean_table <- select(ef_sum, fuel, pol, mean_ef) %>%
                 spread(fuel, mean_ef)
```
* units = mg pollutant emitted per startup event
```{r echo = FALSE}
knitr::kable(ef_mean_table)
```






