---
title: "Startup Emissions - Global Use Estimates"
author: "Kristen Fedak"
date: "August 9, 2017"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: 
      collapsed: false
    theme: yeti
---

# Setup 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

  library(tidyverse)
  library(knitr)

```

# Load and format data
```{r}
 #save output of emissions average g/kg for each material-pollutant from the emissions analysis; load that in.

  population <- read.csv("../supporting data/WorldBank_popestimates.csv", 
                         col.names = c("country", "country_code", "type", "type_code", "yr2013pop", "yr2030pop")) %>% 
                dplyr::select(-country_code, -type_code) 
  population$type <- gsub("population|Population,", "", population$type)
  
  population$yr2013pop <- as.numeric(population$yr2013pop)
  population$yr2030pop <- as.numeric(population$yr2030pop)

  solidfuelusers <- read.csv("../supporting data/WHO_popusingsolidfuels.csv", skip = 2,
                             col.names = c("country", "datasource", "Rural", "Urban", "total")) %>%
                    tidyr::gather("type", "percent_sfusers", -country, -datasource)
 #add line here to add column for < or > symbol. 
  
  solidfuelusers$percent_sfusers <- gsub("&gt;|&lt;", "", solidfuelusers$percent_sfusers) #change <5 and >95 to just 5 and 95. 
  solidfuelusers$percent_sfusers <- gsub("Not available", "NA", solidfuelusers$percent_sfusers)
  solidfuelusers$percent_sfusers <- as.numeric(solidfuelusers$percent_sfusers)
```
