---
title: "Fivegas Data Processing"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  source("../r_scripts/R_tidy.R")
  source("../r_scripts/R_functions.R")
```

# Load data

* fivegas

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  data <- readRDS("../r_files/fivegas.RDS")
```

* sample information

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  test_info <- readRDS("../r_files/test_info.RDS")
```

* sample times

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  times_fuel <- readRDS("../r_files/times_fuel.RDS")
  times_bg <- readRDS("../r_files/times_bg.RDS")
  times_test <- readRDS("../r_files/times_test.RDS")
```

* notes

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  notes <- readRDS("../r_files/notes.RDS")
```

# Convert to longer format

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
 out <- tidyr::gather(data, "pol", "val", 1:5)
```

# Filter times

* full test

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  out_full <- filter_times_startup(times_test, out)
```

* background levels

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  out_bg <- filter_times_background(times_bg, out)
```

* levels by replicate

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  out_rep <- filter_times_rep(times_fuel, out)
```

## Background

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  bg <- dplyr::group_by(out_bg, id, type, pol) %>%
        dplyr::summarise(mean = mean(val, na.rm = TRUE)) %>%
        tidyr::spread(type, mean)
```

# QC

# Save to file

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  saveRDS(out_full, file = "../r_files/fivegas_full.RDS")
  saveRDS(out_bg, file = "../r_files/fivegas_background.RDS")
  saveRDS(out_rep, file = "../r_files/fivegas_byrep.RDS")
```

# Summary

# Plots

* tests

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=40, eval=TRUE}
  ggplot(out_full, aes(datetime, val, color = pol )) + 
    geom_point() +
    scale_y_log10() +
    facet_wrap(~id, ncol = 3, scale = "free") +
    theme_minimal() +
    xlab("") +
    theme(legend.position = "top")
```
* background

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=40, eval=TRUE}
  ggplot(out_bg, aes(datetime, val, color = pol )) + 
    geom_point() +
    scale_y_log10() +
    facet_wrap(~id, ncol = 3, scale = "free") +
    theme_minimal() +
    xlab("") +
    theme(legend.position = "top")
```

* background

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=40, eval=TRUE}
  ggplot(out_rep, aes(datetime, val, color = rep)) + 
    geom_point() +
    scale_y_log10() +
    facet_wrap(~id, ncol = 3, scale = "free") +
    theme_minimal() +
    xlab("") +
    theme(legend.position = "top")
```