---
title: "Fuel Prep"
author: "Jessica Tryner"
date: "December 7, 2018"
output: html_document
---

```{r}
  library(tidyverse)
  library(readxl)
```

```{r}
  fuel_prep <- read_excel("../data/logs/Fuel Prep Final Edited.xlsx")
```

Clean the data:

```{r, warning=FALSE}
  fuel_prep_clean <- dplyr::select(fuel_prep, fuel_id, test_date, test_order, 
                                              mass_final, mass_original,
                                              kiln_wood_original, kiln_wood_post, 
                                              mc_target) %>%
                     dplyr::mutate(test_order         = as.numeric(test_order),
                                   mass_final         = as.numeric(mass_final),
                                   mass_original      = as.numeric(mass_original),
                                   kiln_wood_original = as.numeric(kiln_wood_original),
                                   kiln_wood_post     = as.numeric(kiln_wood_post),
                                   mc_target          = as.numeric(mc_target)) %>%
                     dplyr::filter(!is.na(test_order))
```

Calculate:

1. The moisture content of the reference piece of fuel (on a dry mass basis).  
2. The dry weight of the test fuel.  
3. The actual moisture content of the test fuel (on a dry mass basis).  

```{r}
  fuel_prep_clean <- dplyr::mutate(fuel_prep_clean,
                                   kiln_mc   = (kiln_wood_original - kiln_wood_post)/kiln_wood_post, # dry basis
                                   m_dry     = mass_original/(kiln_mc + 1),
                                   mc_actual = 100*(mass_final - m_dry)/m_dry) # dry basis
```

Save the data: 

```{r}
  saveRDS(fuel_prep_clean, "../r_files/fuel_prep_clean.RDS")
```
