---
title: "Ions"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
  library(knitr)
```

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  source("../r_scripts/R_load_data.R")
  source("../r_scripts/R_load_metadata.R")
  source("../r_scripts/R_tidy.R")
```

# Load data

* load ions

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  ions <- readRDS("../r_files/ions.RDS")
```

* metadata

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  test_info <- readRDS("../r_files/test_info.RDS")
  times_fuel <- readRDS("../r_files/times_fuel.RDS")
  times_bg <- readRDS("../r_files/times_bg.RDS")
  times_test <- readRDS("../r_files/times_test.RDS")
  flow <- readRDS("../r_files/flows.RDS")
  notes <- readRDS("../r_files/notes.RDS")
```

# Organize

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  ions <- tidyr::gather(ions, "var", "val", 2:17) %>%
          dplyr::select(-id)

  info <- dplyr::select(test_info, id_test, id, fuel_type, fuel_quant)

  flow <- dplyr::filter(flow, inst == "carbonyl") %>%
          dplyr::select(id, mean, delta) %>%
          dplyr::rename(flow_mean = mean,
                        flow_delta = delta)

  times <- dplyr::select(times_test, id, start, end)

  ions <- dplyr::left_join(ions, info, by = c("id_ions" = "id_test")) %>%
          dplyr::left_join(flow, by = "id") %>%
          dplyr::left_join(times, by = "id")
```

# QC

* extract notes for ion data (should be carbonlys?)

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  notes <- dplyr::filter(notes, grepl("ions|all", notes) == TRUE)
```

# Concentration calculations

# Background analysis

# Summary

Ion data was collected during `r length(unique(ions$id))` experiments. There is no ion data for tests: `r setdiff(as.character(test_info$id), as.character(ions$id))`.

# Save merged file

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  saveRDS(ions, file = "../r_files/ions_merged.RDS")
```

# Plots

