---
title: "ISEE Poster (Kristen)"
author: "Kristen Fedak"
date: "September 11, 2017"
output: html_document
---

# Setup

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
  library(forcats)
  library(MASS)
  library(GGally)
  library(scales)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Load data and meta data
  emission_factors <- readRDS("../r_files/emission_factors.RDS")
  load("../r_files/samples.Rda")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Load functions
  source("../r_scripts/R_functions.R")
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Add stove/fuel information
  # Use carbon balance method for missing emissions factors
  emissions <- dplyr::left_join(emission_factors, 
                               dplyr::select(samples,
                                             id,
                                             stove, stovecat,
                                             fuel, fuelcat),
                                             by = "id") %>%
               dplyr::filter(metric == "mass_emitted") %>%
               dplyr::mutate(mass_ef_comb = ifelse(is.na(mass_ef),
                                                   mass_c_ef, mass_ef)) %>%
               dplyr::mutate(energy_ef_comb = ifelse(is.na(energy_ef), energy_c_ef,
                                              energy_ef))
```

# Emissions Factors

```{r}
  emissions_factors <- emissions %>% 
                       dplyr::filter(pol == "grav" | pol == "voc_benzene" | pol == "co" |
                                     pol == "formaldehyde" | pol == "acetaldehyde" | pol == "voc_toluene")

  emissions_factors$pol <- forcats::fct_recode(emissions_factors$pol, PM2.5 = "grav",
                                                                  benzene = "voc_benzene",
                                                                  toluene = "voc_toluene",
                                                                  CO = "co")

  emissions_factors$pol <- forcats::fct_relevel(emissions_factors$pol, "PM2.5", "CO",
                                                                   "benzene", "toluene",
                                                                  "formaldehyde", "acetaldehyde")
  emissions_factors$stovecat <- forcats::fct_recode(emissions_factors$stovecat, insulated = "improved",
                                                                                liquid = "advanced")

  emissions_factors$fuel <- factor(tolower(emissions_factors$fuel))
  
  emissions_factors$fuel <- forcats::fct_relevel(emissions_factors$fuel, "oak",
                                                 "eucalyptus",
                                                 "douglas fir",
                                                 "lump hardwood (med.)",
                                                 "lump hardwood (sm.)",
                                                 "coconut charcoal",
                                                 "west slope pellets",
                                                 "eucalyptus pellets",
                                                 "liquefied petroleum gas",
                                                 "kerosene")
```

```{r}
  options(scipen = 999)

  plot <- ggplot(emissions_factors, aes(y = mass_ef_comb, x = stovecat, group = fuel, color = fuel)) +
         geom_point(position = position_dodge(0.5), size = 2) +
         facet_wrap(~pol, ncol = 2, scales = "free") +
         theme_bw() +
         ylab("mg emitted /kg fuel") +
         xlab("stove category") +
         theme(axis.text.x = element_text(angle = 15, hjust = 0.5, vjust = 0.55),
               text = element_text(size=20))
  plot

 
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
 # Remove outliers
  emission_factors <- dplyr::filter(emissions_factors, mass_ef_comb > 0) %>%
                      dplyr::filter(energy_ef_comb > 0)
```

```{r}
 # filter/setup for analysis
  ef_plotdata <- emissions_factors %>%
                 dplyr::select(id, pol, mass_ef_comb, fuel, fuelcat, stove, stovecat) %>%
                 dplyr::distinct() %>%
                 tidyr::spread(pol, mass_ef_comb)
```

# Plot relationships 

```{r, echo=FALSE}
 # function for calculating  r2 value to add to plots
 # fit lm to formula
  lm_mod = function(out = ef_plotdata, fm = "PM2.5 ~ CO"){
    m = lm(fm, out)
    eq <- substitute(~~R^2~"="~r2, 
                     list(r2 = format(summary(m)$r.squared, digits = 2)))
    as.character(as.expression(eq))
  }

```

## PM vs CO

```{r}
 # r2 for all fuels combined
  r2_data <- data.frame(eq = unclass(lm_mod(ef_plotdata, "PM2.5 ~ CO")))

  ggplot(ef_plotdata, aes(x = PM2.5, y = CO)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat, shape = stovecat)) +
      scale_color_hue(l = 55) +
      geom_smooth(method = "lm", se = FALSE, aes(group = fuelcat, color = fuelcat)) +
      geom_text(data = r2_data, aes(x = 5000, y = 2.7e5, label = eq, family = "Helvetica Neue"),
                      color = 'black',  parse = TRUE,
                      size = 6) +
      xlab("PM2.5 EF (mg/kg of fuel)") +
      ylab("CO EF (mg/kg of fuel)") +
      theme_bw() +
      theme(text = element_text(size = 20),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank())

```

```{r}

 #_______________________________________________________________________________
 # r2 for each fuel
  eqns <- by(ef_plotdata, ef_plotdata$fuelcat, lm_mod)
  r2_data <- data.frame(eq = unclass(eqns), fuelcat = as.factor(names(eqns)))
 #_______________________________________________________________________________

  ggplot(ef_plotdata, aes(x = grav, y = co)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = -Inf, y = Inf, label = eq, family = "Helvetica Neue"),
                      color = 'black',  parse = TRUE,
                      vjust = 1.5, hjust = "inward",
                      size = 6) +
      xlab("PM2.5 EF (mg/kg of fuel)") +
      ylab("CO EF (mg/kg of fuel)") +
      theme_bw() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank()) +
      facet_wrap(~fuelcat, scales = "free")

```

## PM vs benzene

```{r}
 # r2 for all fuels combined
  r2_data <- data.frame(eq = unclass(lm_mod(ef_plotdata, "grav ~ voc_benzene")))

  ggplot(ef_plotdata, aes(x = grav, y = voc_benzene)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = 45, y = 1e4, label = eq, family = "Helvetica Neue"),
                      color = 'black',  parse = TRUE,
                      size = 6) +
      xlab("PM2.5 EF (mg/kg of fuel)") +
      ylab("Benzene EF (mg/kg of fuel)") +
      scale_x_log10() +
      theme_bw() +
      scale_y_log10() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank())

```

```{r}

 #_______________________________________________________________________________
 # r2 for each fuel
  eqns <- by(ef_plotdata, ef_plotdata$fuelcat, lm_mod)
  r2_data <- data.frame(eq = unclass(eqns), fuelcat = as.factor(names(eqns)))
 #_______________________________________________________________________________

  ggplot(ef_plotdata, aes(x = grav, y = voc_benzene)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = -Inf, y = Inf, label = eq),
                      color = 'black',  parse = TRUE,
                      vjust = 1.5, hjust = "inward",
                      size = 6) +
      xlab("PM2.5 EF (mg/kg of fuel)") +
      ylab("Benzene EF (mg/kg of fuel)") +
      theme_bw() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank()) +
      facet_wrap(~fuelcat, scales = "free")

```

## PM vs formaldehyde

```{r}
 # r2 for all fuels combined
  r2_data <- data.frame(eq = unclass(lm_mod(ef_plotdata, "grav ~ formaldehyde")))

  ggplot(ef_plotdata, aes(x = grav, y = formaldehyde)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = 45, y = 1500, label = eq, family = "Helvetica Neue"),
                      color = 'black',  parse = TRUE,
                      size = 6) +
      xlab("PM2.5 EF (mg/kg of fuel)") +
      ylab("Formaldehyde EF (mg/kg of fuel)") +
      scale_x_log10() +
      theme_bw() +
      scale_y_log10() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank())

```

```{r}

 #_______________________________________________________________________________
 # r2 for each fuel
  eqns <- by(ef_plotdata, ef_plotdata$fuelcat, lm_mod)
  r2_data <- data.frame(eq = unclass(eqns), fuelcat = as.factor(names(eqns)))
 #_______________________________________________________________________________

  ggplot(ef_plotdata, aes(x = grav, y = formaldehyde)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = -Inf, y = Inf, label = eq),
                      color = 'black',  parse = TRUE,
                      vjust = 1.5, hjust = "inward",
                      size = 6) +
      xlab("PM2.5 EF (mg/kg of fuel)") +
      ylab("Formaldehyde EF (mg/kg of fuel)") +
      theme_bw() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank()) +
      facet_wrap(~fuelcat, scales = "free")

```

## PM vs acetaldehyde

```{r}
 # r2 for all fuels combined
  r2_data <- data.frame(eq = unclass(lm_mod(ef_plotdata, "grav ~ acetaldehyde")))

  ggplot(ef_plotdata, aes(x = grav, y = acetaldehyde)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = 45, y = 1e3, label = eq, family = "Helvetica Neue"),
                      color = 'black',  parse = TRUE,
                      size = 6) +
      xlab("PM2.5 EF (mg/kg of fuel)") +
      ylab("Acetaldehyde EF (mg/kg of fuel)") +
      scale_x_log10() +
      theme_bw() +
      scale_y_log10() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank())

```

```{r}

 #_______________________________________________________________________________
 # r2 for each fuel
  eqns <- by(ef_plotdata, ef_plotdata$fuelcat, lm_mod)
  r2_data <- data.frame(eq = unclass(eqns), fuelcat = as.factor(names(eqns)))
 #_______________________________________________________________________________

  ggplot(ef_plotdata, aes(x = grav, y = acetaldehyde)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = -Inf, y = Inf, label = eq),
                      color = 'black',  parse = TRUE,
                      vjust = 1.5, hjust = "inward",
                      size = 6) +
      xlab("PM2.5 EF (mg/kg of fuel)") +
      ylab("Acetaldehyde EF (mg/kg of fuel)") +
      theme_bw() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank()) +
      facet_wrap(~fuelcat, scales = "free")

```

## CO vs benzene

```{r}
 # r2 for all fuels combined
  r2_data <- data.frame(eq = unclass(lm_mod(ef_plotdata, "co ~ voc_benzene")))

  ggplot(ef_plotdata, aes(x = co, y = voc_benzene)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = 6e3, y = 1.7e3, label = eq, family = "Helvetica Neue"),
                      color = 'black',  parse = TRUE,
                      size = 6) +
      xlab("CO EF (mg/kg of fuel)") +
      ylab("Benzene EF (mg/kg of fuel)") +
      scale_x_log10() +
      theme_bw() +
      scale_y_log10() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank())

```

```{r}

 #_______________________________________________________________________________
 # r2 for each fuel
  eqns <- by(ef_plotdata, ef_plotdata$fuelcat, lm_mod)
  r2_data <- data.frame(eq = unclass(eqns), fuelcat = as.factor(names(eqns)))
 #_______________________________________________________________________________

  ggplot(ef_plotdata, aes(x = co, y = voc_benzene)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = -Inf, y = Inf, label = eq),
                      color = 'black',  parse = TRUE,
                      vjust = 1.5, hjust = "inward",
                      size = 6) +
      xlab("CO EF (mg/kg of fuel)") +
      ylab("Benzene EF (mg/kg of fuel)") +
      theme_bw() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank()) +
      facet_wrap(~fuelcat, scales = "free")

```

## CO vs formaldehyde

```{r}
 # r2 for all fuels combined
  r2_data <- data.frame(eq = unclass(lm_mod(ef_plotdata, "co ~ formaldehyde")))

  ggplot(ef_plotdata, aes(x = co, y = formaldehyde)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = 5e3, y = 1e3, label = eq, family = "Helvetica Neue"),
                      color = 'black',  parse = TRUE,
                      size = 6) +
      xlab("CO EF (mg/kg of fuel)") +
      ylab("Formaldehyde EF (mg/kg of fuel)") +
      scale_x_log10() +
      theme_bw() +
      scale_y_log10() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank())

```

```{r}

 #_______________________________________________________________________________
 # r2 for each fuel
  eqns <- by(ef_plotdata, ef_plotdata$fuelcat, lm_mod)
  r2_data <- data.frame(eq = unclass(eqns), fuelcat = as.factor(names(eqns)))
 #_______________________________________________________________________________

  ggplot(ef_plotdata, aes(x = co, y = formaldehyde)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = -Inf, y = Inf, label = eq),
                      color = 'black',  parse = TRUE,
                      vjust = 1.5, hjust = "inward",
                      size = 6) +
      xlab("CO EF (mg/kg of fuel)") +
      ylab("Formaldehyde EF (mg/kg of fuel)") +
      theme_bw() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank()) +
      facet_wrap(~fuelcat, scales = "free")

```
## CO vs acetaldehyde

```{r}
 # r2 for all fuels combined
  r2_data <- data.frame(eq = unclass(lm_mod(ef_plotdata, "co ~ acetaldehyde")))

  ggplot(ef_plotdata, aes(x = co, y = acetaldehyde)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = 5e3, y = 4e2, label = eq, family = "Helvetica Neue"),
                      color = 'black',  parse = TRUE,
                      size = 6) +
      xlab("CO EF (mg/kg of fuel)") +
      ylab("Acetaldehyde EF (mg/kg of fuel)") +
      scale_x_log10() +
      theme_bw() +
      scale_y_log10() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank())

```

```{r}

 #_______________________________________________________________________________
 # r2 for each fuel
  eqns <- by(ef_plotdata, ef_plotdata$fuelcat, lm_mod)
  r2_data <- data.frame(eq = unclass(eqns), fuelcat = as.factor(names(eqns)))
 #_______________________________________________________________________________

  ggplot(ef_plotdata, aes(x = co, y = acetaldehyde)) + 
      geom_point(size = 3, stroke = 1.5, aes(color = fuelcat)) +
      geom_smooth(method = "lm", se = FALSE, color = "black") +
      geom_text(data = r2_data, aes(x = -Inf, y = Inf, label = eq),
                      color = 'black',  parse = TRUE,
                      vjust = 1.5, hjust = "inward",
                      size = 6) +
      xlab("CO EF (mg/kg of fuel)") +
      ylab("Acetaldehyde EF (mg/kg of fuel)") +
      theme_bw() +
      theme(text = element_text(size = 12),
            legend.key = element_rect(fill = 'white'),
            legend.position = "right",
            legend.title = element_blank()) +
      facet_wrap(~fuelcat, scales = "free")

```

