---
title: "Load and save data"
author: "Nicholas Good"
date: "11/20/2016"
output: html_document
---

## Libraries

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
```

## Source files

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  source("r_scripts/R_load_data.R")
  source("r_scripts/R_load_metadata.R")
  source("r_scripts/R_tidy.R")
  source("r_scripts/R_functions.R")
```

# Pollutant data

## CO2

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  co2_lab <- load.multifile(fldr = "data/co2", pattern = "DILUTION1.csv$", inst = "co2")
    save(co2_lab, file="r_files/co2_lab.Rda")
  
  co2_sample <- load.multifile(fldr = "data/co2", pattern = "DILUTION2.csv$", inst = "co2")
    save(co2_sample, file="r_files/co2_sample.Rda")
    
  co2_lab_sample <- load.multifile(fldr = "data/co2", pattern = "DILUTION.csv$", inst = "co2")
    save(co2_lab_sample, file="r_files/co2_lab_sample.Rda")
```

## ECOC

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  ecoc <- load.singlefiles("ecoc")      # ecoc filter analysis
    save(ecoc,file="r_files/ecoc.Rda")
```  

## Fivegas

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  fivegas_conc <- load.fivegas(type = "conc")
    save(fivegas_conc, file="r_files/fivegas_conc.Rda")
    
  fivegas_volts <- load.fivegas(type = "volts")
    save(fivegas_volts, file="r_files/fivegas_volts.Rda")
    
  fivegas_calibration <- load.fivegas(pattern = "_CALIBRATION_",type = "volts")
    save(fivegas_calibration, file="r_files/fivegas_calibration.Rda")
```

## Gravimetric

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  grav <- load.singlefiles("grav")
    save(grav,file="r_files/grav.Rda")
```

## IONS

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  ions <- load.singlefiles("ions")      # ion filter data
    save(ions,file="r_files/ions.Rda")
```

## PAHS

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}   
  pah <- load.singlefiles("pah")      # pah data
    save(pah,file="r_files/pah.Rda")
```

## PAX

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  pax <- load.multifile(fldr = "data/pax", pattern = "ALLDAY_PAX.csv$", inst = "pax")
    save(pax, file="r_files/pax.Rda")
```

## SCALE

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  scale <- load.multifile(fldr = "data/scale", pattern = "_SCALE.xlsx$", inst = "scale")
    save(scale, file="r_files/scale.Rda")
```

## SMPS

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  smps <- load.multifile(fldr = "data/smps", pattern = "_SMPS.csv$", inst = "smps")
    save(smps,file="r_files/smps.Rda")
```

## TEMP

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  temp <- load.multifile(fldr = "data/temp", pattern = "*", inst = "temp")
    save(temp,file="r_files/temp.Rda")
```

## TRANS

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  trans <- load.singlefiles("trans")    # transmissometer data
    save(trans,file="r_files/trans.Rda")
```
 
## VOC
 
```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  voc <- load.singlefiles("voc")        # voc canister data
    save(voc,file="r_files/voc.Rda")
```

# Metadata

## Sample logs

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  samples <- load.singlefiles("sample") # sample info
    save(samples,file="r_files/samples.Rda")
```

## Batch sample meta data
 
```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}  
  batch <- load.singlefiles("batch")    # batch sampling log
    save(batch,file="r_files/batch.Rda")
```

## Wood sample meta data

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  wood <- load.singlefiles("wood")      # wood sampling log
    save(wood,file="r_files/wood.Rda")
```

## Calibration log 1

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  cal_1 <- load.singlefiles("cal_1")    # meta data
    save(cal_1,file="r_files/cal_1.Rda")
```

## Calibration log 2

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}  
  cal_2 <- load.singlefiles("cal_2")    # meta data
    save(cal_2,file="r_files/cal_2.Rda")
```

## Data log 1

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  data_1 <- load.singlefiles("data_1")  # meta data
    save(data_1,file="r_files/data_1.Rda")
```
 
## Data log 2

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE} 
  data_2 <- load.singlefiles("data_2")  # meta data
    save(data_2,file="r_files/data_2.Rda")
```

