---
title: "Overall Manuscript Analysis"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
  library(forcats)
  library(reshape2)
  library(MASS)
  library(GGally)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Load data and meta data
  load("../r_files/emission_factors.Rda")
  load("../r_files/samples.Rda")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Load functions
  source("../r_scripts/R_functions.R")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Add stove/fuel information
  emission_factors <- dplyr::left_join(emission_factors, 
                                       dplyr::select(samples, id, stove, fuel,
                                                              fuelcat, stovecat),
                                       by = "id")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Use carbon balance method for missing emissions factors
  emission_factors <- dplyr::mutate(emission_factors, 
                                    mass_ef_comb = 
                                      ifelse(is.na(mass_ef),
                                             mass_c_ef, mass_ef)) %>%
                      dplyr::mutate(energy_ef_comb =
                                      ifelse(is.na(energy_ef), energy_c_ef,
                                             energy_ef))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Remove outliers
  emission_factors <- dplyr::filter(emission_factors, mass_ef_comb > 0)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  # Select a subset of pollutants
  emission_factors <- dplyr::filter(emission_factors,
                                    grepl("^grav$|^co$|^formaldehyde$|^acetaldehyde$|
                                          |^levoglucosan$|^voc_benzene$|^voc_toluene$|
                                          |^oc$|^ec$", pol))
```

# Correlation heat maps

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors_w <- dplyr::select(emission_factors, id, pol, mass_ef_comb)

  emission_factors_w$row <- 1:nrow(emission_factors_w)

  emission_factors_w <- tidyr::spread(emission_factors_w, pol, mass_ef_comb) %>%
                        dplyr::group_by(id) %>%
                        dplyr::summarise_each(funs(mean(., na.rm = TRUE)))

  emission_factors_w <- unique(emission_factors_w)
  emission_factors_w <- emission_factors_w[-2]
  emission_factors_w <- emission_factors_w[-1]
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  ef_corr <- round(cor(emission_factors_w, use = "pairwise.complete.obs"),2)
  dd <- as.dist((1 - ef_corr) / 2)
  hc <- hclust(dd)
  ef_corr <-ef_corr[hc$order, hc$order]
  ef_corr[lower.tri(ef_corr)] <- NA
  ef_corr_l <- melt(ef_corr, na.rm = TRUE)
```

## All stove types

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width = 14,  fig.height = 10}
  ggplot(data = ef_corr_l, aes(Var2, Var1, fill = value, label = value))+
    geom_tile(color = "white")+
    geom_text(color = "black", size = 7) +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
    midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 18, hjust = 1),
          axis.text.y = element_text(size = 18),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank(),
          legend.justification = c(1, 0),
          legend.position = c(0.4, 0.8),
          legend.direction = "horizontal", 
          legend.title = element_text(size = 18),
          legend.text = element_text(size = 18)) +
          guides(fill = guide_colorbar(barwidth = 10, barheight = 2,
                title.position = "top", title.hjust = 0.5)) +
    coord_fixed()
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors_wood <- dplyr::filter(emission_factors, fuelcat == "wood")

  emission_factors_w <- dplyr::select(emission_factors_wood, id, pol, mass_ef_comb)

  emission_factors_w$row <- 1:nrow(emission_factors_w)

  emission_factors_w <- tidyr::spread(emission_factors_w, pol, mass_ef_comb) %>%
                        dplyr::group_by(id) %>%
                        dplyr::summarise_each(funs(mean(., na.rm = TRUE)))
  
  emission_factors_w <- unique(emission_factors_w)
  emission_factors_w <- emission_factors_w[-2]
  emission_factors_w <- emission_factors_w[-1]
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  ef_corr <- round(cor(emission_factors_w, use = "pairwise.complete.obs"),2)
  dd <- as.dist((1 - ef_corr) / 2)
  hc <- hclust(dd)
  ef_corr <-ef_corr[hc$order, hc$order]
  ef_corr[lower.tri(ef_corr)] <- NA
  ef_corr_l <- melt(ef_corr, na.rm = TRUE)
```

## Wood fuels

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width = 14,  fig.height = 10}
  ggplot(data = ef_corr_l, aes(Var2, Var1, fill = value, label = value))+
    geom_tile(color = "white")+
    geom_text(color = "black", size = 7) +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
    midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 18, hjust = 1),
          axis.text.y = element_text(size = 18),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank(),
          legend.justification = c(1, 0),
          legend.position = c(0.4, 0.8),
          legend.direction = "horizontal", 
          legend.title = element_text(size = 18),
          legend.text = element_text(size = 18)) +
          guides(fill = guide_colorbar(barwidth = 10, barheight = 2,
                title.position = "top", title.hjust = 0.5)) +
    coord_fixed()
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors_charcoal <- dplyr::filter(emission_factors, fuelcat == "charcoal")

  emission_factors_w <- dplyr::select(emission_factors_charcoal, id, pol, mass_ef_comb)

  emission_factors_w$row <- 1:nrow(emission_factors_w)

  emission_factors_w <- tidyr::spread(emission_factors_w, pol, mass_ef_comb) %>%
                        dplyr::group_by(id) %>%
                        dplyr::summarise_each(funs(mean(., na.rm = TRUE)))
  
  emission_factors_w <- unique(emission_factors_w)
  emission_factors_w <- emission_factors_w[-2]
  emission_factors_w <- emission_factors_w[-1]
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  ef_corr <- round(cor(emission_factors_w, use = "pairwise.complete.obs"),2)
  dd <- as.dist((1 - ef_corr) / 2)
  hc <- hclust(dd)
  ef_corr <-ef_corr[hc$order, hc$order]
  ef_corr[lower.tri(ef_corr)] <- NA
  ef_corr_l <- melt(ef_corr, na.rm = TRUE)
```

## Charcoal fuels

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width = 14,  fig.height = 10}
  ggplot(data = ef_corr_l, aes(Var2, Var1, fill = value, label = value))+
    geom_tile(color = "white")+
    geom_text(color = "black", size = 7) +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
    midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 18, hjust = 1),
          axis.text.y = element_text(size = 18),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank(),
          legend.justification = c(1, 0),
          legend.position = c(0.4, 0.8),
          legend.direction = "horizontal", 
          legend.title = element_text(size = 18),
          legend.text = element_text(size = 18)) +
          guides(fill = guide_colorbar(barwidth = 10, barheight = 2,
                title.position = "top", title.hjust = 0.5)) +
    coord_fixed()
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors_pellets <- dplyr::filter(emission_factors, fuelcat == "pellets")

  emission_factors_w <- dplyr::select(emission_factors_pellets, id, pol, mass_ef_comb)

  emission_factors_w$row <- 1:nrow(emission_factors_w)

  emission_factors_w <- tidyr::spread(emission_factors_w, pol, mass_ef_comb) %>%
                        dplyr::group_by(id) %>%
                        dplyr::summarise_each(funs(mean(., na.rm = TRUE)))
  
  emission_factors_w <- unique(emission_factors_w)
  emission_factors_w <- emission_factors_w[-2]
  emission_factors_w <- emission_factors_w[-1]
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  ef_corr <- round(cor(emission_factors_w, use = "pairwise.complete.obs"),2)
  dd <- as.dist((1 - ef_corr) / 2)
  hc <- hclust(dd)
  ef_corr <-ef_corr[hc$order, hc$order]
  ef_corr[lower.tri(ef_corr)] <- NA
  ef_corr_l <- melt(ef_corr, na.rm = TRUE)
```

## Pellet fuels

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width = 14,  fig.height = 10}
  ggplot(data = ef_corr_l, aes(Var2, Var1, fill = value, label = value))+
    geom_tile(color = "white")+
    geom_text(color = "black", size = 7) +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
    midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 18, hjust = 1),
          axis.text.y = element_text(size = 18),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank(),
          legend.justification = c(1, 0),
          legend.position = c(0.4, 0.8),
          legend.direction = "horizontal", 
          legend.title = element_text(size = 18),
          legend.text = element_text(size = 18)) +
          guides(fill = guide_colorbar(barwidth = 10, barheight = 2,
                title.position = "top", title.hjust = 0.5)) +
    coord_fixed()
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors_advanced <- dplyr::filter(emission_factors, fuelcat == "advanced")

  emission_factors_w <- dplyr::select(emission_factors_advanced, id, pol, mass_ef_comb)

  emission_factors_w$row <- 1:nrow(emission_factors_w)

  emission_factors_w <- tidyr::spread(emission_factors_w, pol, mass_ef_comb) %>%
                        dplyr::group_by(id) %>%
                        dplyr::summarise_each(funs(mean(., na.rm = TRUE)))
  
  emission_factors_w <- unique(emission_factors_w)
  emission_factors_w <- emission_factors_w[-2]
  emission_factors_w <- emission_factors_w[-1]
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  ef_corr <- round(cor(emission_factors_w, use = "pairwise.complete.obs"), 2)
  dd <- as.dist((1 - ef_corr) / 2)
  hc <- hclust(dd)
  ef_corr <-ef_corr[hc$order, hc$order]
  ef_corr[lower.tri(ef_corr)] <- NA
  ef_corr_l <- melt(ef_corr, na.rm = TRUE)
```

## Advanced fuels

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width = 14,  fig.height = 10}
  ggplot(data = ef_corr_l, aes(Var2, Var1, fill = value, label = value))+
    geom_tile(color = "white")+
    geom_text(color = "black", size = 7) +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
    midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 18, hjust = 1),
          axis.text.y = element_text(size = 18),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          axis.ticks = element_blank(),
          legend.justification = c(1, 0),
          legend.position = c(0.4, 0.8),
          legend.direction = "horizontal", 
          legend.title = element_text(size = 18),
          legend.text = element_text(size = 18)) +
          guides(fill = guide_colorbar(barwidth = 10, barheight = 2,
                title.position = "top", title.hjust = 0.5)) +
    coord_fixed()
```

# Correlation pairs

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  emission_factors_w <- dplyr::select(emission_factors, id, pol, mass_ef_comb)

  emission_factors_w$row <- 1:nrow(emission_factors_w)

  emission_factors_w <- tidyr::spread(emission_factors_w, pol, mass_ef_comb) %>%
                        dplyr::group_by(id) %>%
                        dplyr::summarise_each(funs(mean(., na.rm = TRUE))) %>%
                        dplyr::left_join(dplyr::select(emission_factors, id, fuelcat))
  
  emission_factors_w <- unique(emission_factors_w)
  emission_factors_w <- emission_factors_w[-2]
  emission_factors_w <- emission_factors_w[-1]
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width = 14,  fig.height = 40}
  ggduo(
        emission_factors_w,
        mapping = aes(color = fuelcat),
        types = list(continuous = wrap(lm_with_cor, alpha = 0.25)),
        showStrips = FALSE) +
    theme_bw() +
    theme(legend.position = "bottom") 
```