---
title: "PAHs"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  library(tidyverse)
  library(knitr)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/', fig.height = 5, fig.width = 13,
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# Load files

Source files

```{r load_source}
  source("../r_scripts/R_load_data.R")
  source("../r_scripts/R_load_metadata.R")
  source("../r_scripts/R_tidy.R")
```

PAH data

```{r load_data}
  pah_raw <- readRDS("../r_files/pah.RDS")    # pah dataset
  pah_lod <- readRDS("../r_files/pah_lod.RDS")    # pah lod dataset
```

Metadata

```{r load_metadata}
  load("../r_files/data_1.Rda")    # metadata
```

# Merge raw and LOD data

Extract LOD data

```{r}
  lod <- pah_lod %>%
         dplyr::mutate(lod = ifelse(val == "BDL", "below", "above")) %>%
         dplyr::select(id, lod, filter_type, pol)
```

```{r}
  pah <- pah_raw %>% 
         dplyr::left_join(lod, by = c("id", "filter_type", "pol")) %>%
         dplyr::mutate(val = as.numeric(val),
                       val_lod_adj = ifelse(lod == "below", val / sqrt(2), val))
```

# Blank analysis 

Extract blank data

```{r}
  blanks <- pah %>%
            dplyr::filter(grepl("^B", id))
```

# Merge data with metadata

Extract pah filter cartridge data

```{r extract_cartridge_data}
  meta <- data_1 %>%
          dplyr::select(matches("_red|^id$|^date$"))
```

Extra flow rate data

```{r extract_flows}
  flows <- meta %>%
           dplyr::select(matches("flow_|^id$|^date$")) %>%
           tidyr::gather("var", "value", -id, -date) %>%
           dplyr::filter(grepl("_avg$", var)==FALSE) %>%
           dplyr::mutate(type = sub("flow.*", "", var),
                         rep = as.factor(gsub("[^0-9]", "", var))) %>%
           dplyr::select(-var)  %>%
           dplyr::filter(!is.na(id)) %>%
           dplyr::group_by(rep, id, type) %>%
           dplyr::mutate(mean = mean(value, na.rm = TRUE))  %>%
           dplyr::ungroup() %>%
           dplyr::filter(rep == 1) %>%
           dplyr::select(-value, -rep, -date)  %>%
           tidyr::spread(type, mean)
```

Extra time data

```{r extract_times}
  times <- meta %>% 
           dplyr::select(matches("^time_|^id$|^date$")) %>%
           tidyr::gather("var", "value", -id, -date) %>%
           dplyr::mutate(type = ifelse(grepl("_start_", var), "start", "NA"),
                         type = ifelse(grepl("_end_", var), "end", type)) %>%
           dplyr::arrange(id) %>%
           dplyr::filter(!is.na(id)) %>%  
           dplyr::select(-var, -date) %>%  
           tidyr::spread(type, value)
```

Merge pah with filter metadata

```{r}


  pah <- pah_raw %>% 
         dplyr::left_join(lod, by = c("id", "filter_type", "pol")) %>%
         dplyr::left_join(flows, by = "id") %>%
         dplyr::left_join(times, by = "id") %>%  
         dplyr::rename(pre_flow = pre, post_flow = post) %>%
         dplyr::mutate(flow = (pre_flow + post_flow) / 2,
                       val = as.numeric(val),
                       val_lod_adj = ifelse(lod == "below", val / sqrt(2), val))
```

## Plot

* tests

```{r, fig.width=15, fig.height=50}
  p_data <- filter(pah, filter_type == "p" | filter_type == "b" | filter_type == "f", grepl("^[0-9]", pah$id))

  p <-  ggplot(p_data, aes(id, val_lod_adj)) +
        geom_point(aes(color = filter_type)) +
        scale_y_log10() +
        theme_bw() +
        theme(legend.position = "top") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7)) +
        facet_wrap(~pol, ncol = 1)
  p
```

* blanks

```{r, fig.width=15, fig.height=50}


  p <-  ggplot(p_data, aes(id, val_lod_adj)) +
        geom_point(aes(color = filter_type)) +
        scale_y_log10() +
        theme_bw() +
        theme(legend.position = "top") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7)) +
        facet_wrap(~pol, ncol = 1)
  p
```

* lab background

```{r, fig.width=15, fig.height=50}
  p_data <- filter(pah, filter_type == "p" | filter_type == "b" | filter_type == "f", grepl("^G", pah$id))

  p <-  ggplot(p_data, aes(id, val_lod_adj)) +
        geom_point(aes(color = filter_type)) +
        scale_y_log10() +
        theme_bw() +
        theme(legend.position = "top") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7)) +
        facet_wrap(~pol, ncol = 1)
  p
```
 
# Combine filter stages

```{r}
   pah_merged <- pah %>%
                 dplyr::group_by(id, pol, flow, pre_flow, post_flow, start, end) %>%
                 summarise(sum = sum(val_lod_adj, na.rm = TRUE))
```

## Save merged file

```{r}
  saveRDS(pah, file = "../r_files/pah_merged.RDS")
```
