---
title: "SET Calculations"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE)
```

```{r load_libraries, echo=FALSE}
  library(tidyverse)
```

# Load files

* data

```{r load_data, echo=FALSE}
  emissions <- readRDS("../r_files/emissions_long.RDS")
```

* import sample info

```{r load_metadata, echo=FALSE}
  load("../r_files/samples.Rda")
```

# Tidy data

* select pollutants of interest
* select fuels of interest 

```{r}
  pols <- "^co$|^ec$|^oc$|grav|acetaldehyde|formaldehyde|^voc_benzene$|^voc_toluene$"
  fuels <- "Douglas Fir|Liquefied Petroleum Gas|West Slope Pellets"
```

* select concentration measurements 
* join with stove/fuel data 
* calculate average by stove/fuel combo

```{r}
  pol_conc <- emissions %>%
              dplyr::filter(metric == "conc") %>%
              dplyr::filter(qc != "bad") %>%
              dplyr::filter(grepl(pols, pol)) %>%
              dplyr::left_join(dplyr::select(samples, id, stove, fuel)) %>%
              dplyr::filter(grepl(fuels, fuel)) %>%
              dplyr::group_by(stove, pol, inst, metric) %>%
              dplyr::summarise_at("value", median) %>%
              dplyr::mutate(pol = )
```

# Dilution

* define dilution ratios provided by Christian 

```{r}
  dilution <- tibble::data_frame(stove = c("Three Stone Fire (Artisan)",
                                           "Rocket Elbow (Envirofit, G3300)",
                                           "Fan Rocket Elbow (Biolite, HomeStove)",
                                           "Gasifier (Philips, HD4012)",
                                           "Pressurized LPG (WokSmith, WS-C1-25K)"),
                                 ratio = c(28.5, 18.1, 20.0, 18.7, 15)) 
                                           
```

* divide by dilution ratio

```{r}
  pol_conc <- pol_conc %>%
              dplyr::inner_join(dilution, by = "stove") %>%
              dplyr::mutate(diluted_conc = value / ratio)
```

## Pollutant concentrations after dilution

```{r, echo=FALSE}
 table_conc <- pol_conc %>%
               dplyr::ungroup() %>%
               dplyr::select(stove, pol, diluted_conc) %>%
               tidyr::spread(pol, diluted_conc)
```


```{r}
  knitr::kable(table_conc,
               col.names = c("Stove type", "Pollutant", "Diluted concentration (ug/m3)"),
               alight = 'c',
               digits = 2)
```



