---
title: "Startup Manuscript"
output: html_document
---

```{r global_options, include = FALSE}
  knitr::opts_chunk$set(fig.path = 'figures/',
                        warning = FALSE,
                        message = FALSE,
                        fig.width = 10, fig.height = 4,
                        cache = FALSE)
```

```{r setup, include=FALSE}
  library(tidyverse)
  library(knitr)
  source("../r_scripts/R_functions.R")
```

```{r, include=FALSE}
  emission_factors <- readRDS(file = "../r_files/emission_factors.RDS")
```


# Results

## Prepare data

```{r include = FALSE}
# set variable types from character -> factor
# filter out bad QC data
# set fuel type order by survey result "commonality" of use. 
# create variable mass (g) pollutant emitted per startup event
# create variable average mass (g) of startup material per startup event
# filter out backgrounds and blanks
  per_test <- dplyr::mutate(emission_factors, fuel = factor(fuel),
                                                 qc = factor(qc),
                                                 pol = factor(pol)) %>%
                 dplyr::rename(mass_emitted = value) %>%
                 dplyr::select(-metric) %>%
                 dplyr::filter(qc != "bad") %>%
                 dplyr::mutate(fuel = forcats::fct_relevel(fuel, "background",
                                                                 "kerosene",
                                                                 "plastic_bags",
                                                                 "newspaper",
                                                                 "leaves_twigs",
                                                                 "rubber",
                                                                 "flipflops",
                                                                 "t_shirts",
                                                                 "food_packaging",
                                                                 "wood_shims")) %>%
                 dplyr::mutate(fuel_names = forcats::fct_recode(fuel, "plastic bags" = "plastic_bags",
                                                                      "kindling" = "leaves_twigs",
                                                                      "inner tubes" = "rubber",
                                                                      "footwear" = "flipflops",
                                                                      "fabric" = "t_shirts",
                                                                      "wood shims" = "wood_shims",
                                                                      "food packaging" = "food_packaging"),
                            mass_pol_per_startup = (mass_emitted * 1e-3) / fuel_quant, # mg per startup event
                            mass_fuel_per_startup = fuelmass_total / fuel_quant, # g per startup event
                            mass_pol_per_mass_fuel = mass_emitted / fuelmass_total) %>%  # mg/g (same as g/kg)
              dplyr::filter(!grepl("^B", id_test))
```


## Table 1

* experiment summary

```{r}
fuel_sum <- dplyr::filter(per_test, pol == 'grav') %>% 
            dplyr::group_by(fuel_names) %>%
            dplyr::summarize(n_tests = n(),
                             n_events_per_test = round(mean(fuel_quant), 2),
                             min_events_per_test = min(fuel_quant),
                             max_events_per_test = max(fuel_quant),
                             mean_fuel_mass_per_event_g = round(mean(mass_fuel_per_startup), 2),
                             min_fuel_mass_per_event_g = round(min(mass_fuel_per_startup), 1),
                             max_fuel_mass_per_event_g = round(max(mass_fuel_per_startup), 1))

knitr::kable(fuel_sum)
```

## Table 2

* emissions per startup event (mg per startup event)

```{r}
  mean_per_startup <- per_test %>%
                      dplyr::group_by(inst, fuel_names, pol) %>%
                      dplyr::summarize(nreps = n(),
                                   mean = round(mean(mass_pol_per_startup, na.rm = TRUE), 2),
                                   min = round(min(mass_pol_per_startup, na.rm = TRUE), 2),
                                   max = round(max(mass_pol_per_startup, na.rm = TRUE), 2)) %>%
                      dplyr::ungroup()

  mean_per_startup_table <- mean_per_startup %>%
                            dplyr::select(fuel_names, pol, mean, inst) %>%
                            tidyr::spread(fuel_names, mean) %>%
                            dplyr::arrange(inst)
  
  knitr::kable(mean_per_startup_table)
```

## Supplemental Table 1

* emissions per mass fuel (mg per g fuel (same as g/kg))

```{r}
  per_fuel_mass <- per_test %>%
                      dplyr::group_by(inst, fuel_names, pol) %>%
                      dplyr::summarize(nreps = n(),
                                   mean = round(mean(mass_pol_per_mass_fuel, na.rm = TRUE), 2),
                                   min = round(min(mass_pol_per_mass_fuel, na.rm = TRUE), 2),
                                   max = round(max(mass_pol_per_mass_fuel, na.rm = TRUE), 2)) %>%
                      dplyr::ungroup()

  per_fuel_mass_table <- per_fuel_mass %>%
                            dplyr::select(fuel_names, pol, mean, inst) %>%
                            tidyr::spread(fuel_names, mean) %>%
                            dplyr::arrange(inst)
  
  knitr::kable(per_fuel_mass_table)
```

## Figure 1.

* Experimental setup - created in powerpoint

## Figure 2.

* emissions of key pollutants

```{r fig.width = 16, fig.height = 11}
  p_data_key <- dplyr::filter(per_test, grepl('^grav$|^co$|^formaldehyde$|^acetaldehyde$|^voc_benzene$|^voc_toluene$', pol)) %>% #add ECOC when have data
                dplyr::mutate(pol = sub("^voc_", "", pol),
                              pol = sub("^grav", "PM2.5", pol)) %>%
                dplyr::mutate(pol = forcats::fct_relevel(pol, "PM2.5", "co",
                                                      "formaldehyde", "acetaldehyde",
                                                      "benzene", "toluene")) %>%
                dplyr::mutate(fuel_names = forcats::fct_relevel(fuel_names, "kerosene", "kindling",
                                                          "footwear", "inner tubes", "newspaper",
                                                          "wood shims", "fabric", 
                                                          "food packaging", "plastic bags"))


  p_data_key_means <- dplyr::filter(mean_per_startup, grepl('^grav$|^co$|^formaldehyde$|^acetaldehyde$|^voc_benzene$|^voc_toluene$', pol)) %>%
                      dplyr::mutate(pol = sub("^voc_", "", pol),
                                    pol = sub("^grav", "PM2.5", pol))%>%
                      dplyr::mutate(pol = forcats::fct_relevel(pol, "PM2.5", "co",
                                                                    "formaldehyde", "acetaldehyde",
                                                                    "benzene", "toluene"))

  ggplot(p_data_key, aes(fuel_names, mass_pol_per_startup, color = fuel)) +
  geom_point(size = 5) +
  geom_point(data = p_data_key_means, aes(x = fuel_names, y = mean), colour = 'black', size = 6, shape = 8, stroke = 1.5) + 
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size=25),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = 25))) +
  ylab("mg per startup event") + xlab("fuel type") +
  facet_wrap(~pol, scales = "free")
```


## Figure 2

* stacked bar charts of health relevent pollutant categories

```{r fig.width = 12, fig.height = 8}
  pol_cats <- mean_per_startup %>%
              dplyr::filter(pol == "voc_benzene" |
                            pol == "voc_toluene" |
                            pol == "voc_ethylbenzene" |
                            pol == "voc_m_p_xylene" |
                            pol == "voc_o_xylene") %>%
              dplyr::mutate(cat = "BTEX") %>%
              dplyr::bind_rows(dplyr::filter(mean_per_startup,
                                             inst == "carbs") %>%
                              dplyr::mutate(cat = "Carbonyls")) %>%
              dplyr::bind_rows(dplyr::filter(mean_per_startup,
                                             pol == "voc_benzene" |
                                             pol == "voc_toluene" |
                                             pol == "formaldehyde" |
                                             pol == "acetaldehyde") %>%
                              dplyr::mutate(cat = "Carcinogens")) %>%
              dplyr::mutate(pol = sub("^voc_", "", pol),
                            pol = sub(".*xylene.*", "xylenes", pol)) %>%
              dplyr::filter(cat != "Carbonyls")

  ggplot(pol_cats, aes(fuel_names, mean)) +
        geom_col(aes(fill = pol), position = "fill") +
        facet_wrap(~cat, scales = "free") +
        theme_bw() +
        theme(legend.position = "right",text = element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1)) +
        scale_fill_hue(l=65, c=60) +
        theme(legend.title=element_blank(),
              axis.text.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = 25))) +
        ylab("mg per startup event") + 
        xlab("Startup Material") 

```
```
