---
title: "temp"
author: "Nicholas Good"
date: "11/23/2016"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  source("../r_scripts/R_tidy.R")
```

## Load data

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  load("../r_files/temp.Rda")           # temperature dataset
  load(file = "../r_files/samples.Rda") # load sample
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  colnames(temp)
```

## Tidy

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
temp_merged <- dplyr::select(temp, -ch2, -ch3) %>%
          tidyr::gather(var, val, tamb, thood) %>%
          dplyr::arrange(id)
```

## Save merged file

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  save(temp_merged, file = "../r_files/temp_merged.Rda")
```

## Plot

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=40}
  ggplot(temp_merged, aes(datetime, val, color = var)) +
  geom_line() +
  geom_point() +
  facet_wrap(~id, ncol = 3, scales = "free") +
  theme_minimal()
```

## Summary

$Temperature$ was measured for `r length(unique(temp_merged$id))` experiments between `r min(temp_merged$date, na.rm = TRUE)` and `r max(temp_merged$date, na.rm = TRUE)`. There is no $temperature$ data for tests: `r setdiff(as.character(samples$id), as.character(temp_merged$id))`.
