---
title: "Fuel burned"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, kableExtra)
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# load files

load data

```{r}
  samples <- readRDS("../../r_data/samples.RDS")
  batch <- readRDS("../../r_data/batch_wgts.RDS")
  wood <- readRDS("../../r_data/wood_wgts.RDS")
```

# fuel mass calculations

## batch stoves

fuel consumed

```{r}
  batch_mass <- dplyr::filter(batch, var == "fuel" |
                                     var == "refueled" |
                                     var == "preshutdown") %>%
                tidyr::spread(var, value) %>%
                dplyr::rename(wgt_fuel = fuel,
                              wgt_refuel = refueled,
                              wgt_shutdown = preshutdown) %>%
                dplyr::mutate(mass_fuel = wgt_fuel + wgt_refuel - wgt_shutdown)
```

## wood stoves

fuel consumed

```{r}
  wood_mass <- dplyr::filter(wood, var == "fuel" |
                                   var == "ashpot_unusedfuel" |
                                   var == "ashpot_char_ash" |
                                   var == "ashpot_lid") %>%
                tidyr::spread(var, value) %>%
                dplyr::rename(wgt_fuel = fuel,
                              wgt_pot_unusedfuel = ashpot_unusedfuel,
                              wgt_pot_char_ash = ashpot_char_ash,
                              wgt_pot = ashpot_lid) %>%
                dplyr::mutate(mass_fuel = wgt_fuel -
                                          wgt_pot_unusedfuel -
                                          wgt_pot_char_ash +
                                          2 * wgt_pot)
```

## merge batch and wood fuel

```{r}
  fuel_burnt <- dplyr::bind_rows(dplyr::select(batch_mass, id, mass_fuel),
                                 dplyr::select(wood_mass, id, mass_fuel)) %>%
                dplyr::mutate(id = as.factor(id)) %>%
                dplyr::filter(grepl("^[0-9]", id) == TRUE)
```

# plot: fuel burnt

```{r, echo=FALSE}
  fuel_burnt %>%
  dplyr::left_join(samples) %>%
  dplyr::filter(grepl("^[0-9]", id) == TRUE) %>%
  ggplot(aes(x = stove, y = mass_fuel, color = fuel)) +
        geom_point() +
        theme_bw() + 
        theme(axis.text.x = element_text(angle = 25, hjust = 1)) +
        theme(legend.position = "top") +
        facet_grid(~fuelcat, space = "free", scales = "free") +
        ylab("fuel burnt (grams)")
```

## table: missing data

```{r, echo = FALSE}
  dplyr::select(samples, id, stove, fuel) %>%
  dplyr::anti_join(fuel_burnt %>%
                   dplyr::select(id) %>%
                   dplyr::distinct(),
                   by = "id") %>%
    dplyr::filter(!grepl("G", id)) %>%
    knitr::kable("markdown", align = 'c')
```

# save

```{r}
  saveRDS(fuel_burnt, file = "../../r_data/fuel_burnt.RDS")
```