---
title: "Constants"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, knitr, forcats)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE)
```

```{r}
  source("../../scripts/functions.R")
```

# hood flow

```{r}
  hood_flow <- 4  # m^3/min

  saveRDS(hood_flow, file = "../../r_data/hood_flow.RDS")
```

# fuel properties

```{r}
  fuel_properties <- tibble::data_frame(fuel = c("douglas fir",
                                                 "eucalyptus",
                                                 "oak",
                                                 "coconut charcoal",
                                                 "lump hardwood (med.)",
                                                 "lump hardwood (sm.)",
                                                 "eucalyptus pellets",
                                                 "west slope pellets",
                                                 "kerosene",
                                                 "lpg"),
                                         lhv = c(18658, 19427, 18658, 16628,
                                                 28611, 28611, 17501, 17501,
                                                 43100, 46100),  # kJ/kg
                                         carbon_fraction = c(0.497733333, 0.521166667,
                                                             0.5, 0.488, 0.840833333,
                                                             0.840833333, 0.4852,
                                                             0.4852, 0.82, 0.82))  # kg_C/kg_fuel

  saveRDS(fuel_properties, file = "../../r_data/fuel_properties.RDS")
```

# molecular formula and weight 

```{r}
  pol_properties <- tibble::data_frame(pol = c ("co2", "co", "ch4", "ec", "oc",
                                                "tc", "grav", "ultrafines",
                                                "ethane", "ethene",
                                                "propane", "propene",
                                                "i_butane", "n_butane",
                                                "ethyne", "t_2_butene",
                                                "1_butene", "i_butene",
                                                "c_2_butene", "cyclopentane",
                                                "i_pentane", "n_pentane",
                                                "t_2_pentene",
                                                "2_methyl_2_butene",
                                                "1_pentene", "c_2_pentene",
                                                "cyclohexane", "n_hexane",
                                                "isoprene", "1_hexene",
                                                "c_2_hexene",
                                                "2_4_dimethylpentane",
                                                "methylcyclohexane",
                                                "n_heptane", "benzene",
                                                "3_methylpentane",
                                                "2_3_dimethylpentane",
                                                "2_methylhexane",
                                                "3_methylhexane",
                                                "2_2_4_trimethylpentane",
                                                "2_3_4_trimethylpentane",
                                                "toluene", "2_methylheptane",
                                                "3_methylheptane", "n_octane",
                                                "ethylbenzene", "m_p_xylene",
                                                "styrene", "o_xylene",
                                                "n_nonane", "i_propylbenzene",
                                                "a_pinene", "n_propylbenzene",
                                                "3_ethyltoluene", "4_ethyltoluene",
                                                "1_3_5_trimethylbenzene",
                                                "2_ethyltoluene",
                                                "1_2_4_trimethylbenzene",
                                                "n_decane",
                                                "1_2_3_trimethylbenzene",
                                                "1_3_diethylbenzene",
                                                "1_4_diethylbenzene",
                                                "1_2_diethylbenzene",
                                                "levoglucosan", "mannosan",
                                                "galactosan", "galactose",
                                                "glucose", "mannose",
                                                "glycerol", "threitol",
                                                "mannitol", "arabinose",
                                                "xylose", "wsoc", "sodium",
                                                "ammonium", "potassium",
                                                "magnesium", "calcium",
                                                "chloride", "nitrite",
                                                "nitrate", "sulfate",
                                                "formaldehyde",
                                                "acetaldehyde",
                                                "acetone", "acrolein",
                                                "propionaldehyde",
                                                "crotonaldehyde",
                                                "butanone", "methacrolein",
                                                "butyraldehyde", "benzaldehyde",
                                                "isovaleraldehyde", "valeraldehyde",
                                                "o_tolualdehyde", "m_p_tolualdehyde",
                                                "hexaldehyde", "2_5_dimethylbenzaldehyde"),
                                       num_c = c(1, 1, 1, NA, NA, NA, NA, NA,
                                                 2, 2, 3, 3, 4, 4, 2,
                                                 4, 4, 4, 4, 5, 5, 5, 5, 5,
                                                 5, 5, 6, 6, 5, 6, 6, 7, 7,
                                                 7, 6, 6, 7, 7, 7, 8, 8, 7,
                                                 8, 8, 8, 8, 8, 8, 8, 9, 9,
                                                 10, 9, 9, 9, 9, 9, 9, 10,
                                                 9, 10, 10, 10, 6, 6, 6, 6,
                                                 6, 6, 3, 4, 6, 5, 5, NA, 0,
                                                 0, 0, 0, 0, 0, 0, 0, 0, 1,
                                                 2, 3, 3, 3, 4, 4, 4, 4, 7,
                                                 5, 5, 8, 8, 6, 9),
                                       num_h = c(0, 0, 4, NA, NA, NA, NA, NA,
                                                 6, 4, 8, 6, 10, 10,
                                                 2, 8, 8, 8, 8, 10, 12, 12,
                                                 10, 10, 10, 10, 12, 14, 8,
                                                 12, 12, 16, 14, 16, 6,
                                                 14, 16, 16, 16, 18, 18,
                                                 8, 18, 18, 18, 10, 10,
                                                 8, 10, 20, 12, 16, 12,
                                                 12, 12, 12, 12, 12, 22,
                                                 12, 14, 14, 14, 10, 10,
                                                 10, 12, 12, 12, 8, 10,
                                                 14, 10, 10, NA, 0, 4,
                                                 0, 0, 0, 0, 0, 0, 0, 2,
                                                 4, 6, 4, 6, 6, 8, 6, 8,
                                                 6, 10, 10, 8, 8, 12, 10),
                                       num_o = c(2, 1, 0, NA, NA, NA,
                                                 NA, NA, 0, 0, 0, 0, 0,
                                                 0, 0, 0, 0, 0, 0, 0, 0,
                                                 0, 0, 0, 0, 0, 0, 0, 0,
                                                 0, 0, 0, 0, 0, 0, 0, 0,
                                                 0, 0, 0, 0, 0, 0, 0, 0,
                                                 0, 0, 0, 0, 0, 0, 0, 0,
                                                 0, 0, 0, 0, 0, 0, 0, 0,
                                                 0, 0, 5, 5, 5, 6, 6, 6,
                                                 3, 4, 6, 5, 5, NA, 0,
                                                 0, 0, 0, 0, 0, 2, 3, 4,
                                                 1, 1, 1, 1, 1, 1, 1, 1,
                                                 1, 1, 1, 1, 1, 1, 1, 1),
                                       ions = c(NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, "Na",
                                                 "N", "K", "Mg", "Ca", "Cl",
                                                 "N", "N", "S", NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA, NA, NA,
                                                 NA, NA, NA, NA, NA))

  pol_properties <- dplyr::mutate(pol_properties, mw = calc_mw(pol_properties)) %>%
                    dplyr::select(pol, mw, num_c)

  mw_c <- 12.0106

  saveRDS(pol_properties, file = "../../r_data/pol_properties.RDS")
  saveRDS( mw_c, file = "../../r_data/mw_c.RDS")
```

# instrument constants

```{r}
  filter_area <- 11.34  # cm^2 (updated on 5/15/2018 by KB)
  voc_flow <- 0.0135  # L/min
  smps_dlogdp <- 0.015625355  # dlogDp

  saveRDS(filter_area, file = "../../r_data/filter_area.RDS") 
  saveRDS(voc_flow, file = "../../r_data/voc_flow.RDS")
  saveRDS(smps_dlogdp, file = "../../r_data/smps_constant.RDS")
```

# thermodynamic properties

```{r}
  hfg_water <- 2257  # J/g
  c_water <- 4.186  # J/g C
  gas_constant <- 8.314  # J/K mol

  saveRDS(hfg_water, file = "../../r_data/hfg_water.RDS")
  saveRDS(c_water, file = "../../r_data/c_water.RDS")
  saveRDS(gas_constant, file = "../../r_data/gas_constant.RDS")
```