---
title: "External data groupings"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  library(tidyverse)
  library(forcats) #meow!
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE)
```

```{r load_data}
  wbt_data <- readRDS("../../r_data/wbt_data.RDS")
  field_data <- readRDS("../../r_data/field_data.RDS")
  rose_data <- readRDS("../../r_data/rose_field_data.RDS")
```

# wbt data

```{r}
  wbt_data <- 
    wbt_data %>%
    dplyr::mutate(stove = 
                    stove %>%
                    forcats::fct_recode("Rocket elbow" = "envirofit g3300",
                                        "Rocket elbow" = "gyapa",
                                        "Built-in plancha" = "onil",
                                        "Built-in plancha" = "patsari",
                                        "Rocket elbow" = "stovetec greenfire",
                                        "Rocket elbow" = "improved no chimney",
                                        "Metal jiko" = "metal charcoal",
                                        "Ceramic jiko" = "ceramic charcoal",
                                        "Ceramic jiko" = "kcj standard",
                                        "Gasifier" = "philips fan",
                                        "Three-stone fire" = "traditional",
                                        "Three-stone fire" = "three stone fire",
                                        "Rocket elbow" = "improved no chimney",
                                        "Forced-draft gasifier" = "gasifier",
                                        "Built-in plancha" = "ecostufa")) %>%
    dplyr::mutate(study = gsub("_", " et al, ", study),
                  pol = gsub("pm2.5", "pm_mass", pol)) %>%
    dplyr::filter(var == "mean", grepl("pm|co|ec", pol), units == "grams per kilogram")
```

# field data

```{r}
  field_data <- 
    field_data %>%
    dplyr::mutate(stove = gsub(".*philips.*", "gasifier", stove),
                  stove = gsub(".*ace.*", "forced-draft gasifier", stove),
                  fuel = gsub(".charcoal.*", "charcoal (local)", fuel),
                  fuel = gsub(".*wood.*", "wood (collected)", fuel)) %>%
    dplyr::filter(grepl("rocket elbow|^gasifier|three stone fire", stove)) %>%
    dplyr::mutate(test_type = "Field")
```

```{r}
  saveRDS(wbt_data, "../../r_data/wbt_data_merged.RDS")
  saveRDS(field_data, "../../r_data/field_data_merged.RDS")
```
