---
title: "Stove-fuel groupings"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, knitr, forcats)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE)
```

* load data

```{r load_files}
  samples <- readRDS("../../r_data/samples.RDS")
```

# stove types

```{r}
  samples <- dplyr::mutate(samples,
                           stove =
                             stove %>%
                             as_factor %>%
                              tolower %>%
                              gsub(" [:(:].*[:):]", "", .) %>%
                              forcats::fct_relevel("three stone fire",
                                                   "clay ring",
                                                   "ceramic charcoal",
                                                   "rocket elbow",
                                                   "built-in justa",
                                                   "metal charcoal",
                                                   "fan rocket elbow",
                                                   "gasifier",
                                                   "wick kerosene",
                                                   "pressurized kerosene",
                                                   "pressurized lpg") %>%
                               forcats::fct_recode("three-stone fire" = "three stone fire") %>%
                               forcats::fct_recode("fan rocket-elbow" = "fan rocket elbow") %>%
                               forcats::fct_recode("lpg" = "pressurized lpg") %>%
                               forcats::fct_recode("built-in plancha" = "built-in justa") %>%
                               forcats::fct_recode("pressure kerosene" = "pressurized kerosene") %>%
                               forcats::fct_recode("forced-draft gasifier" = "gasifier") %>%
                               forcats::fct_recode("chulha" = "clay ring"))
```

# fuel types

```{r}
  samples <- dplyr::mutate(samples,
                           fuel = 
                             fuel %>%
                             as_factor %>%
                             tolower %>%
                             forcats::fct_recode("lpg" = "liquefied petroleum gas") %>%
                             forcats::fct_relevel("oak",
                                                   "eucalyptus",
                                                   "douglas fir",
                                                   "lump hardwood (med.)",
                                                   "lump hardwood (sm.)",
                                                   "coconut charcoal",
                                                   "west slope pellets",
                                                   "eucalyptus pellets",
                                                   "lpg",
                                                   "kerosene"))
```

# fuel categories

```{r}
  samples <- dplyr::mutate(samples,
                           fuelcat =
                             forcats::fct_collapse(fuel,
                               "unprocessed wood" = c("oak",
                                                      "eucalyptus",
                                                      "douglas fir"),
                               "charcoal" = c("coconut charcoal",
                                              "lump hardwood (med.)", 
                                              "lump hardwood (sm.)"),
                               "processed wood" = c("eucalyptus pellets",
                                                    "west slope pellets"),
                               "kerosene" = c("kerosene"),
                               "lpg" = c("lpg")))
```

# stove categories

```{r}
  samples <- dplyr::mutate(samples,
                           stovecat =
                            forcats::fct_collapse(stove,
                               "wood" = c("three-stone fire",
                                          "clay ring",
                                          "rocket elbow",
                                          "built-in plancha",
                                          "fan rocket-elbow",
                                          "gasifier"),
                               "charcoal" = c("ceramic charcoal",
                                              "metal charcoal"),
                               "fossil fuel stoves" = c("wick kerosene",
                                                        "pressure kerosene",
                                                        "lpg")))
```

* save info

```{r}
  saveRDS(samples, "../../r_data/samples.RDS")
```

```{r}
  samples <-
    samples %>%
    dplyr::filter(fuelcat != "background") %>%
    dplyr::select(id, stove, fuel, fuelcat) %>%
    dplyr::arrange(id)

  readr::write_csv(samples, "../../qaqc_files/test_ids.csv")
```

