---
title: "Process transmissometer data"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, kableExtra)
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

## load files

load scripts

```{r}
  source("../../scripts/tidy.R")
```

load data

```{r}
  grav <- readRDS("../../r_data/grav.RDS")
  filter_area <- readRDS("../../r_data/filter_area.RDS")
  trans <- readRDS("../../r_data/trans.RDS")
  times <- readRDS("../../r_data/filter_times.RDS")
  flows <- readRDS("../../r_data/filter_flows.RDS")
  notes <- readRDS("../../r_data/notes.RDS")
  samples <- readRDS("../../r_data/samples.RDS")
```

load schemes

```{r}
  qc_colors <- readRDS("../../r_data/qc_colors.RDS")
  lod_shapes <- readRDS("../../r_data/lod_shapes.RDS")
```

## get filter id numbers

```{r}
  filter_ids <- dplyr::select(grav, id, id_filter)
```

# merge data with id

```{r}
  trans_merged <- dplyr::left_join(trans, filter_ids, "id_filter") %>%
                  dplyr::mutate(id = as.factor(id))
```

## filters without matches

```{r}
  trans_no_match <- dplyr::anti_join(dplyr::select(filter_ids, id_filter),
                                     dplyr::select(trans, id_filter),
                                     by = "id_filter")
```

## long format

```{r}
  trans_merged <- dplyr::filter(trans_merged, grepl("^[0-9]|^G[0-9]", id) == TRUE) %>%
                  tidyr::gather_("var", "val", grep("^ir|^uv", colnames(trans_merged), value = TRUE)) %>%
                  dplyr::mutate(lamda = sub("_.*", "", var)) %>%
                  dplyr::mutate(pos = sub(".*_", "", var)) %>%
                  dplyr::mutate(type = gsub(".*_(.*)_.*","\\1", var))
```

## flags

extract flags

```{r}
  notes <- 
    notes %>%
    dplyr::filter(grepl("ecoc|all", inst) == TRUE)
```

bad preceeds maybe preceeds good

```{r}
  flags <-
    notes %>%
    dplyr::select(id, qc) %>%
    dplyr::group_by(id) %>%
    dplyr::arrange(qc) %>%
    dplyr::summarise(qc = first(qc))
```

add flag by id

```{r}
  trans_merged <-
    trans_merged %>%
    dplyr::left_join(flags, by = "id") %>%
    dplyr::mutate(id = as.factor(id)) %>%
    dplyr::mutate(qc = as.factor(ifelse(is.na(qc), "ok", as.character(qc))))
```

# save

```{r}
  saveRDS(trans_merged, file = "../../r_data/trans_merged.Rda")
```

## plot: time series of lab blanks

```{r, echo=FALSE, fig.width=12, fig.height=8}
 trans_merged %>%
    dplyr::filter(var == "ir_front_sample_post", !grepl("G", id)) %>%
    dplyr::left_join(dplyr::select(samples, id, stove, fuel, fuelcat), by = "id") %>%
    dplyr::filter(fuelcat == "wood") %>%
    ggplot(aes_string(x = "id", y = "val")) +
      geom_point(aes(color = qc), size = 2) +
      scale_color_manual(values = qc_colors) +
      theme_bw() +
      theme(text = element_text(size = 16),
            legend.position = "top") +
      facet_wrap(stove~fuel, scales = "free", ncol = 4) +
      ylab("atn")
```

notes: data is expected to be missing for: 17A only. This filter ruptured during the test so was not able to be transmissometer-ed.
