---
title: "figure 3: carcinogenic compounds"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, pals, devtools, patchwork, RColorBrewer)
  #devtools::install_github("thomasp85/patchwork")
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

load data

```{r}
  emissions <- readRDS("../../../r_data/emissions_factors.RDS")
  samples <- readRDS("../../../r_data/samples.RDS")
  pol_properties <- readRDS("../../../r_data/pol_properties.RDS")
```

## format stove names

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = 
                    stove %>% 
                    factor %>% 
                    forcats::fct_relevel("three-stone fire",
                                         "chulha",
                                         "rocket elbow",
                                         "built-in plancha",
                                         "fan rocket-elbow",
                                         "forced-draft gasifier",
                                         "ceramic charcoal",
                                         "metal charcoal",
                                         "wick kerosene",
                                         "pressure kerosene",
                                         "lpg") %>%
                    forcats::fct_recode("Three-stone\nfire" = "three-stone fire",
                                         "Mud\nchulha" = "chulha",
                                         "Rocket\nelbow" = "rocket elbow",
                                         "Built-in\nplancha" = "built-in plancha",
                                         "Fan rocket\neblow" = "fan rocket-elbow",
                                         "Gasifier" = "forced-draft gasifier",
                                         "Ceramic\njiko" = "ceramic charcoal",
                                          "Metal\njiko" = "metal charcoal",
                                          "Wick\nkerosene" = "wick kerosene",
                                         "Pressure\nkerosene" = "pressure kerosene",
                                          "LPG" = "lpg"))
```

## add stove fuel info

```{r}
  emissions <-
    emissions %>%
    dplyr::left_join(samples %>%
                       dplyr::select(id, stove, fuel, stovecat, fuelcat), by = "id")
```

## filter out values below background

```{r}
  emissions <-
    emissions %>%
    dplyr::filter(bg != "below")
```

## select pollutants

```{r}
  gases <-
    emissions %>%
    dplyr::filter(grepl("^benzene|formaldehyde|styrene|acetaldehyde|isoprene", pol)) %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

```{r}
  particles <-
    emissions %>%
    dplyr::filter(grepl("b.a.pyrene|dibenzo.*anthracene|cyclopenta.*pyrene|b.*anthracene|b...fluoranthene|indeno", pol)) %>%
    dplyr::filter(metric == "energy_delivered_ef") %>%
    dplyr::mutate(pol = gsub("indeno\\(1,2,3\\) cd pyrene", "indeno\\[1,2,3-cd\\]pyrene", pol),
                  pol = gsub("\\(ah\\)",  "\\[a,h\\]", pol),
                  pol = gsub("b\\[",  "benzo\\[", pol),
                  pol = gsub("b\\[",  "benzo\\[", pol),
                  pol = gsub("benzo\\[a\\]anthracene",  "benz\\[a\\]anthracene", pol))
```

# check for outliers

## gases

```{r, echo=FALSE, fig.width=10, fig.height=8, eval=FALSE}
  gases %>%
    dplyr::group_by(id) %>%
    dplyr::mutate(val = sum(val, na.rm = TRUE)) %>%
    ggplot(aes(x = id, y = val, color = fuel)) +
    geom_point() +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "top") +
    facet_wrap(~stove, scales = "free")
```

## particles

```{r, echo=FALSE, eval=FALSE,fig.width=10, fig.height=8}
  particles %>%
    dplyr::group_by(id) %>%
    dplyr::mutate(val = sum(val, na.rm = TRUE)) %>%
    ggplot(aes(x = id, y = val, color = fuel)) +
    geom_point() +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "top") +
    facet_wrap(~stove, scales = "free")
```

## calculate stats

```{r}
  stats_gases <-
    gases %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

```{r}
  stats_particles <-
    particles %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

## calculate means by pollutant

```{r}
  gases_p <-
    gases %>%
    dplyr::group_by(pol, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::left_join(dplyr::select(pol_properties, pol, mw), by = "pol") %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_category = "gas-phase carcinogens")
```

```{r}
  particles_p <-
    particles %>%
    dplyr::group_by(pol, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::left_join(dplyr::select(pol_properties, pol, mw), by = "pol") %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_category = "particle-phase carcinogens")
```

# figures

```{r, echo=FALSE, fig.width=12, fig.height=4}
    gases_p %>%
    dplyr::mutate(pol_category = "Gas-Phase Carcinogens") %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = forcats::fct_reorder(pol, mw, .desc = TRUE)), stat = "identity") +
      geom_text(data = stats_gases,
                aes(x = stove, y = val, label = sym), stroke = 2, size = 10, angle = 90, nudge_x = -0.05) +
      theme_minimal() +
      scale_fill_manual(values = c("gold3", "mediumseagreen", "palegoldenrod", "dodgerblue1", "dodgerblue3"),
                        name = "gas-phase carcinogens") +
      scale_y_continuous(limits = c(0, 250)) +
      guides(fill = guide_legend(ncol = 2, byrow = FALSE)) +
      annotate("text", x = 2, y = 250, label = "363", size = 5) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = c(1, 1),
            axis.text.y = element_text(size = 16),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size = 14),
            legend.title = element_blank(), 
            legend.spacing.x = unit(0.25, 'cm'), 
            legend.spacing.y = unit(0.25, 'cm')) +
    ylab(expression(paste('miligrams per ', MJ[delivered])))
```

```{r, echo=FALSE, fig.width=12, fig.height=4}
    particles_p %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol, order = pol), stat = "identity") +
      geom_text(data = stats_particles,
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("plum4", "plum", "yellowgreen", "darkorchid",
                                   "lightsteelblue4", "lavender", "orange", "orangered4")) +
      theme_minimal() +
      scale_y_continuous(limits = c(0, 5)) +
      guides(fill = guide_legend(ncol = 2, byrow = FALSE)) +
      annotate("text", x = 1, y = 5, label = "7.16", size = 5) +
      annotate("text", x = 2, y = 5, label = "10.9", size = 5) +
      annotate("text", x = 3, y = 5, label = "14.8", size = 5) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = c(1, 1),
            axis.text.y = element_text(size = 16),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size = 14),
            legend.title = element_blank(), 
            legend.spacing.x = unit(0.25, 'cm'),
            legend.spacing.y = unit(0.25, 'cm')) +
    ylab(expression(paste('miligrams per ', MJ[delivered])))
```