---
title: "figure 2: gas emissions"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, pals, devtools, patchwork, RColorBrewer)
  #devtools::install_github("thomasp85/patchwork")
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

load data

```{r}
  emissions <- readRDS("../../../r_data/emissions_factors.RDS")
  samples <- readRDS("../../../r_data/samples.RDS")
  pol_properties <- readRDS("../../../r_data/pol_properties.RDS")
```

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = 
                    stove %>% 
                    factor %>% 
                    forcats::fct_relevel("three-stone fire",
                                         "chulha",
                                         "rocket elbow",
                                         "built-in plancha",
                                         "fan rocket-elbow",
                                         "forced-draft gasifier",
                                         "ceramic charcoal",
                                         "metal charcoal",
                                         "wick kerosene",
                                         "pressure kerosene",
                                         "lpg") %>%
                    forcats::fct_recode("Three-stone\nfire" = "three-stone fire",
                                         "Mud\nchulha" = "chulha",
                                         "Rocket\nelbow" = "rocket elbow",
                                         "Built-in\nplancha" = "built-in plancha",
                                         "Fan rocket\neblow" = "fan rocket-elbow",
                                         "Gasifier" = "forced-draft gasifier",
                                         "Ceramic\njiko" = "ceramic charcoal",
                                          "Metal\njiko" = "metal charcoal",
                                          "Wick\nkerosene" = "wick kerosene",
                                         "Pressure\nkerosene" = "pressure kerosene",
                                          "LPG" = "lpg"))
```

## add stove fuel info

```{r}
  emissions <-
    emissions %>%
    dplyr::left_join(samples %>%
                       dplyr::select(id, stove, fuel, stovecat, fuelcat), by = "id") %>%
    dplyr::filter(!is.na(val))
```

## filter out values below background

```{r}
  emissions <-
    emissions %>%
    dplyr::mutate(val = ifelse(bg == "below", 0, val))
```

## rename pollutants

```{r}
  emissions <-
    emissions %>%
    dplyr::mutate(pol_category = ifelse(grepl("vocs", pol_category), "volatile organic compounds", pol_category),
                  pol_category = ifelse(grepl("pahs", pol_category), "polycyclic aromatic hydrocarbons", pol_category))
```

## select pollutants

```{r}
  carbonyls <-
    emissions %>%
    dplyr::filter(grepl("carbonyls", pol_category)) %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

```{r}
  vocs <-
    emissions %>%
    dplyr::filter(grepl("volatile organic compounds", pol_category)) %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

## select pollutants

```{r}
  pahs <-
    emissions %>%
    dplyr::filter(grepl("aromatic", pol_category), pol != "naphthalene") %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

## remove tests

```{r}
  vocs <- 
    vocs %>%
    dplyr::filter(id != "5A", id != "9A")
```

notes: need to look at these tests still

## calculate stats

```{r}
  stats_carbs <-
    carbonyls %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

```{r}
  stat_vocs <-
    vocs %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

```{r}
  stats_pahs <-
    pahs %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

## calculate means by pollutant

```{r}
  carbonyls_p <-
    carbonyls %>%
    dplyr::group_by(id, pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_subcategory = 
                    pol_subcategory %>% 
                    factor %>% 
                    fct_recode("saturated aldehydes " = "saturated aldehydes",
                               "unsaturated aldehydes " = "unsaturated aldehydes",
                               "aromatic aldehydes " = "aromatic aldehydes",
                               "ketones " = "ketones") %>% 
                    forcats::fct_relevel("saturated aldehydes ",
                                         "unsaturated aldehydes ",
                                         "aromatic aldehydes ",
                                         "ketones ") %>%
                    forcats::fct_rev(),
                  pol_category = "carbonyls")
```

```{r}
  vocs_p <-
    vocs %>%
    dplyr::group_by(id, pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_subcategory = 
                    pol_subcategory %>%
                    factor %>% 
                    fct_recode("alkanes " = "alkanes",
                               "alkenes " = "alkenes",
                               "alkynes " = "alkynes",
                               "aromatics " = "aromatics") %>%
                    forcats::fct_relevel("alkanes ",
                                         "alkenes ",
                                         "alkynes ",
                                         "aromatics ") %>%
                    forcats::fct_rev(),
                  pol_category = "volatile organic compounds")
```

```{r}
  pahs_p <-
    pahs %>%
    dplyr::group_by(id, pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_subcategory = 
                    pol_subcategory %>% 
                    factor %>% 
                    fct_recode("three rings " = "three rings",
                               "four rings " = "four rings",
                               "five rings " = "five rings",
                               "six rings " = "six rings") %>%
                    forcats::fct_relevel("three rings ",
                                         "four rings ",
                                         "five rings ",
                                         "six rings ") %>%
                    forcats::fct_rev(),
                  pol_category = "polycyclic aromatic hydrocarbons")
```

# figures

```{r, echo=FALSE, fig.width=12, fig.height=4}
  col_vector = c("cornflowerblue",
                 "khaki",
                 "slateblue3",
                 "#9e9ac8")

    carbonyls_p %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
      geom_text(data = stats_carbs,
                aes(x = stove, y = val, label = sym), stroke = 2, size = 10, angle = 90, nudge_x = -0.05) +
      theme_minimal() +
      scale_fill_manual(values = col_vector) +
      guides(fill = guide_legend(nrow = 2, byrow = FALSE)) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = c(1, 1),
            axis.text.y = element_text(size = 16),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size = 14),
            legend.title = element_blank(), 
            legend.spacing.x = unit(0.25, 'cm'), 
            legend.spacing.y = unit(0.25, 'cm')) +
    ylab(expression(paste('miligrams per ', MJ[delivered])))
```

```{r, echo=FALSE, fig.width=12, fig.height=4}
    vocs_p %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
      geom_text(data = stat_vocs,
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("#fc8d62", "coral3", "slategray2", "#0072B2"),
                        name = "VOCs") +
      scale_y_continuous(limits = c(0, 2000)) +
      annotate("text", x = 1, y = 2000, label = "2251", size = 5) +
      annotate("text", x = 2, y = 2000, label = "3254", size = 5) +
      theme_minimal() +
      guides(fill = guide_legend(nrow = 2, byrow = FALSE)) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = c(1, 1),
            axis.text.y = element_text(size = 16),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size = 14),
            legend.title = element_blank(), 
            legend.spacing.x = unit(0.25, 'cm'), 
            legend.spacing.y = unit(0.25, 'cm')) +
    ylab(expression(paste('miligrams per ', MJ[delivered])))
```

```{r, echo=FALSE, fig.width=12, fig.height=4}
    pahs_p %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
      geom_text(data = stats_pahs,
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("gray36", "grey", "darkcyan", "yellowgreen")) +
      scale_y_continuous(limits = c(0, 30)) +
      annotate("text", x = 1, y = 30, label = "36.1", size = 5) +
      annotate("text", x = 2, y = 30, label = "56.3", size = 5) +
      annotate("text", x = 3, y = 30, label = "73.6", size = 5) +
      theme_minimal() +
      guides(fill = guide_legend(nrow = 2, byrow = FALSE)) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = c(1, 1),
            axis.text.y = element_text(size = 16),
            axis.text.x = element_text(size = 14),
            axis.title.x = element_blank(),
            legend.title = element_blank(), 
            legend.spacing.x = unit(0.25, 'cm'), 
            legend.spacing.y = unit(0.25, 'cm')) +
    ylab(expression(paste('miligrams per ', MJ[delivered])))
```