---
title: "gbd"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, pals, devtools, patchwork, RColorBrewer)
  #devtools::install_github("thomasp85/patchwork")
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

load data

```{r}
  gbd <- readRDS("../../../../r_data/gbd.RDS")
```

```{r gbd, fig.width=10, fig.height=4, dpi=200}
  gbd_p <-
    gbd %>%
    dplyr::filter(measure == "Deaths") %>%
    dplyr::group_by(risk_factor) %>%
    dplyr::summarise(value = sum(value, na.rm = TRUE)) %>%
    dplyr::filter(value > 2370000)

  gbd_p %>%
    ggplot(aes(x = reorder(risk_factor, value), y = value)) +
      geom_histogram(stat = "identity", fill = "plum4") +
      geom_histogram(data = gbd_p %>%
                              dplyr::filter(grepl("Household", risk_factor)),
                     aes(x = risk_factor, y = value),
                         stat = "identity", fill = "yellowgreen") +
      geom_histogram(data = gbd_p %>%
                              dplyr::filter(grepl("Ambient", risk_factor)),
                     aes(x = risk_factor, y = value),
                         stat = "identity", fill = "yellowgreen") +
      coord_flip() +
      theme_minimal() +
      theme(text = element_text(size = 14),
            axis.title.y = element_blank()) +
      ylab("Annual Premature Deaths")
```

