---
title: "Figure 3: Ultrafines and PAHs"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, pals, devtools, patchwork, RColorBrewer)
  #devtools::install_github("thomasp85/patchwork")
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

load data

```{r}
  emissions <- readRDS("../../../r_data/emissions_factors.RDS")
  samples <- readRDS("../../../r_data/samples.RDS")
  pol_properties <- readRDS("../../../r_data/pol_properties.RDS")
```

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = 
                    stove %>% 
                    factor %>% 
                    forcats::fct_relevel("three-stone fire",
                                         "chulha",
                                         "rocket elbow",
                                         "built-in plancha",
                                         "fan rocket-elbow",
                                         "forced-draft gasifier",
                                         "ceramic charcoal",
                                         "metal charcoal",
                                         "wick kerosene",
                                         "pressure kerosene",
                                         "lpg") %>%
                    forcats::fct_recode("Three-stone\nfire" = "three-stone fire",
                                         "Mud\nchulha" = "chulha",
                                         "Rocket\nelbow" = "rocket elbow",
                                         "Built-in\nplancha" = "built-in plancha",
                                         "Fan rocket\nelbow" = "fan rocket-elbow",
                                         "Gasifier" = "forced-draft gasifier",
                                         "Ceramic\njiko" = "ceramic charcoal",
                                          "Metal\njiko" = "metal charcoal",
                                          "Wick\nkerosene" = "wick kerosene",
                                         "Pressure\nkerosene" = "pressure kerosene",
                                          "LPG" = "lpg"))
```

## add stove fuel info

```{r}
  emissions <-
    emissions %>%
    dplyr::left_join(samples %>%
                       dplyr::select(id, stove, fuel, stovecat, fuelcat), by = "id")
```

```{r}
  emissions <-
    emissions %>%
    dplyr::filter(pol != "cyclopenta[ce]phenanthrylene")
```

## filter out values below background

```{r}
  emissions <-
    emissions %>%
    dplyr::mutate(val = ifelse(bg == "below", 0, val))
```

## rename pollutants

```{r}
  emissions <-
    emissions %>%
    dplyr::mutate(pol_category = ifelse(grepl("pahs", pol_category),
                                        "polycyclic aromatic hydrocarbons", pol_category))
```

## select pollutants

```{r}
  ultrafines <-
    emissions %>%
    dplyr::filter(grepl("ultrafines", pol)) %>%
    dplyr::filter(metric == "energy_delivered_ef") %>%
    dplyr::mutate(pol_category = "ultrafine particles",
                  pol = "ultrafine particles")
```

```{r}
  pahs <-
    emissions %>%
    dplyr::filter(grepl("aromatic", pol_category), pol != "naphthalene") %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

## calculate stats

```{r}
  range_ultrafines <-
    ultrafines %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE),
                     mean = mean(val, na.rm = TRUE),
                     median = median(val, na.rm = TRUE))
```

```{r}
  stats_pahs <-
    pahs %>%
    dplyr::group_by(id, stove) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE),
                     mean = mean(val, na.rm = TRUE),
                     median = median(val, na.rm = TRUE))
```

## calculate means by pollutant

```{r}
  ultrafines_p <-
    ultrafines %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::mutate(pol_category = "ultrafine particles")
```


```{r}
  pahs_p <-
    pahs %>%
    dplyr::group_by(id, pol_subcategory, stove) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(pol_subcategory, stove) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_subcategory = 
                    pol_subcategory %>% 
                    factor %>% 
                    fct_recode("three rings " = "three rings",
                               "four rings " = "four rings",
                               "five rings " = "five rings",
                               "six rings " = "six rings") %>%
                    forcats::fct_relevel("three rings ",
                                         "four rings ",
                                         "five rings ",
                                         "six rings ") %>%
                    forcats::fct_rev(),
                  pol_category = "polycyclic aromatic hydrocarbons")
```

# figures

```{r, echo=FALSE}
  p1 <- 
    range_ultrafines %>%
      ggplot(aes(x = stove, y = mean)) +
      geom_histogram(data = ultrafines_p, aes(x = stove, y = val), stat = "identity", fill = "plum3", alpha=0.9) +
      geom_boxplot(data = ultrafines, aes(x = stove, y = val), fill = "transparent",
                   color = "gray30", width=0.4, outlier.shape = NA, coef = 0) +
      geom_jitter(data = ultrafines, aes(x = stove, y = val), shape = 1, width = 0.1, size = 1.5, stroke = 1, color = "gray30") +
      #geom_point(aes(x = stove, y = mean), shape = 8, size = 2, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_point(aes(x = stove, y = min), shape = 24, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_point(aes(x = stove, y = max), shape = 25, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_errorbar(data = range_ultrafines, aes(x = stove, ymin = lq, ymax = uq), 
      #              color = "gray30", width = 0.1) +
    #geom_text(data = range_ultrafines,
      #          aes(x = stove, y = val, label = sym), stroke = 2, size = 8, angle = 90, nudge_x = -0.05,
      #          color = "gray30") +
        theme_minimal() +
        #scale_y_continuous(trans = "log10", limits = c(1e5, 1e8), breaks = c(1e5, 1e6, 1e7, 1e8)) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = c(1, 1),
            axis.text.y = element_text(size = 16),
            axis.title.x = element_blank(),
            legend.title = element_blank()) +
      ylab(expression(atop(paste('Ultrafine Particles'), paste('particles per Megajoul', e[delivered]))))
```

```{r, echo=FALSE}
pahs_all <-
  pahs %>%
  dplyr::group_by(id, stove, fuel) %>%
  dplyr::summarise(val = sum(val, na.rm = TRUE))
  
  p2 <-
      pahs_p %>%
      ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity", alpha=0.9) +
      geom_boxplot(data = pahs_all, aes(x = stove, y = val),
                   color = "gray30", width=0.41, fill = "transparent", outlier.shape = NA, coef = 0) +
    geom_jitter(data = pahs_all, aes(x = stove, y = val), shape = 1, width = 0.1, size = 1.5, stroke = 1, color = "gray30") +
      #geom_dotplot(data = pahs_all, aes(x = stove, y = val), binaxis='y', stackdir='center',dotsize = 0.3, fill = "gray30") + 
      #geom_errorbar(data = stats_pahs, aes(x = stove, y = mean, ymin = lq, ymax = uq),
      #              color = "gray30", width = 0.1) +
      #geom_point(data = stats_pahs, aes(x = stove, y = mean), shape = 8, size = 2, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_point(data = stats_pahs, aes(x = stove, y = min), shape = 24, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_point(data = stats_pahs, aes(x = stove, y = max), shape = 25, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_text(data = stats_pahs %>%
      #            dplyr::filter(var != "mean"),
      #          aes(x = stove, y = val, label = sym), size = 8, angle = 90, nudge_x = -0.02,
      #          color = "gray30") +
      scale_fill_manual(values = c("skyblue3", "grey", "darkcyan", "yellowgreen")) +
      scale_y_continuous(limits = c(0, 60)) +
      #annotate("text", x = 1, y = 46, label = "35", size = 5) +
      #annotate("text", x = 2, y = 45, label = "55", size = 5) +
      annotate("text", x = 3, y = 60, label = "73", size = 5) +
      theme_minimal() +
      guides(fill = guide_legend(order = 2,nrow = 2, byrow = FALSE),
             shape = guide_legend(order = 1)) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = c(1, 1),
            axis.text.y = element_text(size = 16),
            axis.title.x = element_blank(),
            legend.title = element_blank(), 
            legend.spacing.x = unit(0.25, 'cm'), 
            legend.spacing.y = unit(0.25, 'cm')) +
    ylab(expression(atop(paste('Polycyclic Aromatic Hydrocarbons'), paste('miligrams per Megajoul', e[delivered]))))
```

```{r figure_3, echo=FALSE, fig.width=12, fig.height=8, dpi=400, dev='pdf'}
  p1 + p2 + plot_layout(nrow = 2, heights = c(1, 1))
```

```{r figure_3a, echo=FALSE, fig.width=12, fig.height=1.75, dpi=400, dev='pdf'}
    range_ultrafines %>%
      ggplot(aes(x = stove, y = val)) +
      geom_histogram(data = ultrafines_p, stat = "identity", fill = "plum3", alpha=0.9) +
      geom_boxplot(data = ultrafines, aes(x = stove, y = val), fill = "transparent",
                   color = "gray30", width=0.4, fill = "transparent", outlier.shape = NA, coef = 0) +
    geom_jitter(data = ultrafines, aes(x = stove, y = val), shape = 1, width = 0.1, size = 1.5, stroke = 1, color = "gray30") +
      #geom_point(aes(x = stove, y = mean), shape = 1, size = 2, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_point(aes(x = stove, y = min), shape = 24, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_point(aes(x = stove, y = max), shape = 25, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_errorbar(data = range_ultrafines, aes(x = stove, ymin = lq, ymax = uq),
                    #color = "gray30", width = 0.1) +
        theme_minimal() +
      scale_y_continuous(limits = c(0, 3.5e14), position = "right") +
      #annotate("text", x = 11, y = 3.5e14, label = "3.5e+14", size = 5) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = c(1, 1),
            axis.text.y = element_text(size = 16),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.title.y = element_text(colour = "white"),
            legend.title = element_blank()) +
      ylab(expression(atop(paste('Ultrafine Particles'), paste('particles per Megajoul', e[delivered]))))
```

```{r figure_3b, echo=FALSE, fig.width=12, fig.height=1.75, dpi=400, dev='pdf'}
      pahs_p %>%
      ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity", alpha=0.9) +
      geom_boxplot(data = pahs_all, aes(x = stove, y = val),
                   fill = "transparent", outlier.shape = NA, coef = 0) +
    geom_jitter(data = pahs_all, aes(x = stove, y = val), shape = 1, width = 0.1, size = 1.5, stroke = 1, color = "gray30") +
      #geom_point(data = stats_pahs, aes(x = stove, y = min), shape = 24, color = "gray30", fill = "gray30", stroke = 1) +
      #geom_point(data = stats_pahs, aes(x = stove, y = max), shape = 25, color = "gray30", fill = "gray30", stroke = 1) +
      scale_fill_manual(values = c("skyblue3", "grey", "darkcyan", "yellowgreen")) +
      scale_y_continuous(limits = c(0, 0.6), position = "right") +
      annotate("text", x = 9, y = 2, label = "2.9", size = 5) +
      theme_minimal() +
      guides(fill = guide_legend(nrow = 2, byrow = FALSE)) +
      theme(text = element_text(size = 18),
            legend.justification = c(1, 1), 
            legend.position = "none",
            axis.text.y = element_text(size = 16),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.title.y = element_text(colour = "white"),
            legend.title = element_blank(), 
            legend.spacing.x = unit(0.25, 'cm'), 
            legend.spacing.y = unit(0.25, 'cm')) +
    ylab(expression(atop(paste('Polycyclic Aromatic Hydrocarbons'), paste('miligrams per Megajoul', e[delivered]))))
```



# summary

## percent reductions

Ultrafines

```{r, echo=FALSE}
  three_stone <- 
    ultrafines_p %>%
    dplyr::filter(stove == "Three-stone\nfire")
    

  ultrafines_p %>%
    dplyr::mutate(three_stone = three_stone$val[1]) %>%
    dplyr::mutate(prct_decrease = ((three_stone - val) / three_stone) * 100,
                  abs_decrease = val - three_stone) %>%
    dplyr::select(stove, prct_decrease, abs_decrease) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(stove = gsub("\n", " ", stove)) %>%
    knitr::kable("markdown", digits = 0, align = 'c')
```

PAHs

```{r, echo=FALSE}
  three_stone <- 
    stats_pahs %>%
    dplyr::filter(stove == "Three-stone\nfire")
    

  stats_pahs %>%
    dplyr::mutate(three_stone = three_stone$mean) %>%
    dplyr::mutate(prct_decrease = ((three_stone - mean) / three_stone) * 100,
                  abs_decrease = mean - three_stone) %>%
    dplyr::select(stove, prct_decrease, abs_decrease) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(stove = gsub("\n", " ", stove)) %>%
    knitr::kable("markdown", digits = 2, align = 'c')
```

## ultrafines

average ultrafines by stove type

```{r, echo=FALSE}
  ultrafines %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(mean = mean(val, na.rm = TRUE),
                     min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    dplyr::mutate(stove = gsub("\n", " ", stove)) %>%
    dplyr::arrange(mean) %>%
    dplyr::mutate_if(is.numeric, funs(as.character(signif(., 2)))) %>%
    knitr::kable("markdown", digits = 2, align = 'c')
```

## pahs

average total pahs by stove type

```{r, echo=FALSE}
  pahs %>%
    dplyr::group_by(id, stove) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(mean = mean(val, na.rm = TRUE),
                     min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    dplyr::mutate(stove = gsub("\n", " ", stove)) %>%
    dplyr::arrange(mean) %>%
    dplyr::mutate_if(is.numeric, funs(as.character(signif(., 2)))) %>%
    knitr::kable("markdown", digits = 2, align = 'c')
```

three ring

```{r, echo=FALSE}
  three_ring <-
    pahs_p %>%
    dplyr::mutate(pol_subcategory = as.character(pol_subcategory)) %>%
    dplyr::filter(grepl("three", pol_subcategory)) %>%
    dplyr::select(stove, val)

  pahs_p %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(total = sum(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::left_join(three_ring, by = "stove") %>%
    dplyr::mutate(ratio = (val / total) * 100) %>%
    dplyr::select(stove, ratio) %>%
    dplyr::mutate(stove = gsub("\n", " ", stove)) %>%
    knitr::kable("markdown", digits = 0, align = 'c')
```

four ring

```{r, echo=FALSE}
  four_ring <-
    pahs_p %>%
    dplyr::mutate(pol_subcategory = as.character(pol_subcategory)) %>%
    dplyr::filter(grepl("four", pol_subcategory)) %>%
    dplyr::select(stove, val)

  pahs_p %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(total = sum(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::left_join(four_ring, by = "stove") %>%
    dplyr::mutate(ratio = (val / total) * 100) %>%
    dplyr::select(stove, ratio) %>%
    dplyr::mutate(stove = gsub("\n", " ", stove)) %>%
    knitr::kable("markdown", digits = 0, align = 'c')
```

five ring

```{r, echo=FALSE}
  five_ring <-
    pahs_p %>%
    dplyr::mutate(pol_subcategory = as.character(pol_subcategory)) %>%
    dplyr::filter(grepl("five", pol_subcategory)) %>%
    dplyr::select(stove, val)

  pahs_p %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(total = sum(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::left_join(five_ring, by = "stove") %>%
    dplyr::mutate(ratio = (val / total) * 100) %>%
    dplyr::select(stove, ratio) %>%
    dplyr::mutate(stove = gsub("\n", " ", stove)) %>%
    knitr::kable("markdown", digits = 0, align = 'c')
```

six ring

```{r, echo=FALSE}
  six_ring <-
    pahs_p %>%
    dplyr::mutate(pol_subcategory = as.character(pol_subcategory)) %>%
    dplyr::filter(grepl("six", pol_subcategory)) %>%
    dplyr::select(stove, val)

  pahs_p %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(total = sum(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::left_join(six_ring, by = "stove") %>%
    dplyr::mutate(ratio = (val / total) * 100) %>%
    dplyr::select(stove, ratio) %>%
    dplyr::mutate(stove = gsub("\n", " ", stove)) %>%
    knitr::kable("markdown", digits = 0, align = 'c')
```