---
title: "figure 2: gas emissions"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, pals, devtools, patchwork, RColorBrewer)
  #devtools::install_github("thomasp85/patchwork")
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

load data

```{r}
  emissions <- readRDS("../../../r_data/emissions_factors.RDS")
  samples <- readRDS("../../../r_data/samples.RDS")
  pol_properties <- readRDS("../../../r_data/pol_properties.RDS")
```

## format stove names

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = 
                    stove %>% 
                    factor %>% 
                    gsub(" ", "\n",.) %>% 
                    forcats::fct_relevel("three\nstone\nfire",
                                         "clay\nring",
                                         "ceramic\ncharcoal",
                                         "rocket\nelbow",
                                         "built-in\nplancha",
                                         "metal\ncharcoal",
                                         "fan\nrocket\nelbow",
                                         "gasifier",
                                         "wick\nkerosene",
                                         "pressure\nkerosene",
                                         "lpg"))
```

## add stove fuel info

```{r}
  emissions <-
    emissions %>%
    dplyr::left_join(samples %>%
                       dplyr::select(id, stove, fuel, stovecat, fuelcat), by = "id")
```

## rename pollutants

```{r}
  emissions <-
    emissions %>%
    dplyr::mutate(pol_category = ifelse(grepl("vocs", pol_category), "volatile organic compounds", pol_category),
                  pol_category = ifelse(grepl("pahs", pol_category), "polycyclic aromatic hydrocarbons", pol_category))
```

## select pollutants

```{r}
  carbonyls <-
    emissions %>%
    dplyr::filter(grepl("carbonyls", pol_category)) %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

```{r}
  vocs <-
    emissions %>%
    dplyr::filter(grepl("volatile organic compounds", pol_category)) %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

## select pollutants

```{r}
  pahs <-
    emissions %>%
    dplyr::filter(grepl("aromatic", pol_category)) %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

# check for outliers

## carbonyls

```{r, echo=FALSE, fig.width=10, fig.height=8, eval=FALSE}
  carbonyls %>%
    dplyr::group_by(id) %>%
    dplyr::mutate(val = sum(val, na.rm = TRUE)) %>%
    ggplot(aes(x = id, y = val, color = fuel)) +
    geom_point() +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "top") +
    facet_wrap(~stove, scales = "free")
```

## vocs

```{r, echo=FALSE, eval=FALSE,fig.width=10, fig.height=8}
  vocs %>%
    dplyr::group_by(id) %>%
    dplyr::mutate(val = sum(val, na.rm = TRUE)) %>%
    ggplot(aes(x = id, y = val, color = fuel)) +
    geom_point() +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "top") +
    facet_wrap(~stove, scales = "free")
```

## pahs

```{r, echo=FALSE, eval=FALSE, fig.width=10, fig.height=8}
  pahs %>%
    dplyr::group_by(id) %>%
    dplyr::mutate(val = sum(val, na.rm = TRUE)) %>%
    ggplot(aes(x = id, y = val, color = fuel)) +
    geom_point() +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "top") +
    facet_wrap(~stove, scales = "free")
```

## remove tests

```{r}
  vocs <- 
    vocs %>%
    dplyr::filter(id != "5A", id != "9A")
```

## calculate stats

```{r}
  stats_carbs <-
    carbonyls %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

```{r}
  stat_vocs <-
    vocs %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

```{r}
  stats_pahs <-
    pahs %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

## calculate means by pollutant

```{r}
  carbonyls <-
    carbonyls %>%
    dplyr::group_by(pol, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::left_join(dplyr::select(pol_properties, pol, mw), by = "pol") %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol = ifelse(grepl("2_5_", pol), "2,5-dimethylbenzaldehyde", pol),
                  pol = ifelse(grepl("o_", pol), "o-tolualdehyde", pol),
                  pol = ifelse(grepl("m_", pol), "m,p-tolualdehyde", pol),
                  pol_category = "carbonyls")
```

```{r}
  vocs <-
    vocs %>%
    dplyr::group_by(id, pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_subcategory = 
                    pol_subcategory %>% 
                    factor %>% 
                    forcats::fct_relevel("alkanes",
                                         "alkenes",
                                         "alkynes",
                                         "aromatics") %>%
                    forcats::fct_rev(),
                  pol_category = "volatile organic compounds")
```

```{r}
  pahs <-
    pahs %>%
    dplyr::group_by(id, pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(pol_subcategory, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_subcategory = 
                    pol_subcategory %>% 
                    factor %>% 
                    forcats::fct_relevel("three rings",
                                         "four rings",
                                         "five rings",
                                         "six rings") %>%
                    forcats::fct_rev(),
                  pol_category = "polycyclic aromatic hydrocarbons")
```

# figures

```{r, echo=FALSE}
  col_vector = c("slateblue1",
                 "slateblue4",
                 "grey",
                 "gray36",
                 "khaki",
                 "khaki4",
                 "cornflowerblue",
                 "dodgerblue4",
                 "indianred1",
                 "indianred4",
                 "seagreen1",
                 "seagreen4",
                 "plum1",
                 "plum4",
                 "yellowgreen",
                 "forestgreen")

  p1 <-
    carbonyls %>%
    dplyr::filter(grepl("traditional", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = forcats::fct_reorder(pol, mw, .desc = TRUE)), stat = "identity") +
      geom_text(data = stats_carbs %>%
                dplyr::filter(grepl("traditional", stovecat)),
                aes(x = stove, y = val, label = sym), stroke = 2, size = 10, angle = 90, nudge_x = -0.05) +
      scale_y_continuous(limits = c(0, 250)) +
      scale_fill_manual(values = col_vector) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.title.y = element_text(size = 16),
            axis.text.y = element_text(size = 18),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            legend.position = "none") +
      guides(fill = guide_legend(title = NULL)) +
      facet_wrap(~stovecat, scales = "free") +
      ylab("mg emitted per MJ delivered")

  p2 <-
    carbonyls %>%
    dplyr::filter(grepl("improved", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = forcats::fct_reorder(pol, mw, .desc = TRUE)), stat = "identity") +
      geom_text(data = stats_carbs %>%
                dplyr::filter(grepl("improved", stovecat)),
                aes(x = stove, y = val, label = sym), stroke = 2, size = 10, angle = 90, nudge_x = -0.05) +
      theme_bw() +
      scale_fill_manual(values = col_vector) +
      theme(text = element_text(size = 20),
            axis.text.y = element_text(size = 18),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            legend.position = "none") +
      guides(fill = guide_legend(title = NULL)) +
      facet_wrap(~stovecat, scales = "free")
  
  p3 <-
    carbonyls %>%
    dplyr::filter(grepl("liquid", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = forcats::fct_reorder(pol, mw, .desc = TRUE)), stat = "identity") +
      geom_text(data = stats_carbs %>%
                dplyr::filter(grepl("liquid", stovecat)),
                aes(x = stove, y = val, label = sym), stroke = 2, size = 10, angle = 90, nudge_x = -0.05) +
      theme_bw() +
      scale_fill_manual(values = col_vector) +
      scale_y_continuous(limits = c(0, 100)) +
      theme(text = element_text(size = 20),
            axis.text.y = element_text(size = 18),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            legend.position = "right",
            legend.text = element_text(size = 12)) +
      guides(fill = guide_legend(title = NULL)) +
      facet_grid(pol_category~stovecat, scales = "free")
```

```{r, echo=FALSE}
  p4 <-
    vocs %>%
    dplyr::filter(grepl("traditional", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
        geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
        geom_text(data = stat_vocs %>%
                  dplyr::filter(grepl("traditional", stovecat)),
                  aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
        scale_fill_manual(values = c("#fc8d62", "coral3", "slategray2", "#0072B2")) +
        scale_y_continuous(limits = c(0, 3500)) +
        theme_bw() +
        theme(text = element_text(size = 20),
              axis.title.y = element_text(size = 16),
              axis.text.y = element_text(size = 18),
              strip.text.x = element_blank(),
              axis.title.x = element_blank(),
              axis.text.x = element_blank(),
              legend.position = "none") +
        guides(fill = guide_legend(title = NULL)) +
        facet_wrap(~stovecat, scales = "free") +
        ylab("mg emitted per MJ delivered") +
        xlab("")

  p5 <-
    vocs %>%
    dplyr::filter(grepl("improved", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
        geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
        geom_text(data = stat_vocs %>%
                  dplyr::filter(grepl("improved", stovecat)),
                  aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
        scale_fill_manual(values = c("#fc8d62", "coral3", "slategray2", "#0072B2")) +
        scale_y_continuous(limits = c(0, 1000)) +
        theme_bw() +
        theme(text = element_text(size = 20),
              axis.text.y = element_text(size = 18),
              strip.text.x = element_blank(),
              axis.title.y = element_blank(),
              axis.title.x = element_blank(),
              axis.text.x = element_blank(),
              legend.position = "none") +
        guides(fill = guide_legend(title = NULL)) +
        facet_wrap(~stovecat, scales = "free")
  
  p6 <-
    vocs %>%
    dplyr::filter(grepl("liquid", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
      geom_text(data = stat_vocs %>%
                dplyr::filter(grepl("liquid", stovecat)),
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("#fc8d62", "coral3", "slategray2", "#0072B2")) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.text.y = element_text(size = 18),
            strip.text.y = element_text(size = 16),
            strip.text.x = element_blank(),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            legend.position = "right",
            legend.text = element_text(size = 12)) +
      guides(fill = guide_legend(title = NULL)) +
      facet_grid(pol_category~stovecat, scales = "free")
```

```{r, echo=FALSE}
  p7 <-
    pahs %>%
    dplyr::filter(grepl("traditional", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
      geom_text(data = stats_pahs %>%
                dplyr::filter(grepl("traditional", stovecat)),
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_y_continuous(limits = c(0, 60)) +
      scale_fill_manual(values = c("slateblue1", "lavender", "yellowgreen", "darkcyan")) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.title.y = element_text(size = 16),
            axis.title.x = element_blank(),
            axis.text.y = element_text(size = 18),
            strip.text.x = element_blank(),
            legend.position = "none") +
      guides(fill = guide_legend(title = NULL)) +
      facet_wrap(~stovecat, scales = "free") +
      ylab("mg emitted per MJ delivered")

  p8 <-
    pahs %>%
    dplyr::filter(grepl("improved", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
      geom_text(data = stats_pahs %>%
                dplyr::filter(grepl("improved", stovecat)),
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("slateblue1", "lavender", "yellowgreen", "darkcyan")) +
      scale_y_continuous(limits = c(0, 80)) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.title.x = element_blank(),
            axis.text.y = element_text(size = 18),
            axis.title.y = element_blank(),
            strip.text.x = element_blank(),
            legend.position = "none") +
      guides(fill = guide_legend(title = NULL)) +
      facet_wrap(~stovecat, scales = "free")
  
  p9 <-
    pahs %>%
    dplyr::filter(grepl("liquid", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol_subcategory, order = pol_subcategory), stat = "identity") +
      geom_text(data = stats_pahs %>%
                dplyr::filter(grepl("liquid", stovecat)),
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("slateblue1", "lavender", "yellowgreen", "darkcyan")) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.text.y = element_text(size = 18),
            strip.text.y = element_text(size = 12),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            strip.text.x = element_blank(),
            legend.position = "right",
            legend.text = element_text(size = 12)) +
      guides(fill = guide_legend(title = NULL)) +
      facet_grid(pol_category~stovecat, scales = "free")
```

```{r figure_1b, echo=FALSE, fig.width=16, fig.height=10}
 (p1 + p2 + p3) +
  p4 + p5 + p6 +
  p7 + p8 + p9 + plot_layout(ncol = 3, widths = c(1, 1.5, 1))
```