---
title: "figure 3: carcinogenic compounds"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, pals, devtools, patchwork, RColorBrewer)
  #devtools::install_github("thomasp85/patchwork")
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

load data

```{r}
  emissions <- readRDS("../../../r_data/emissions_factors.RDS")
  samples <- readRDS("../../../r_data/samples.RDS")
  pol_properties <- readRDS("../../../r_data/pol_properties.RDS")
```

## format stove names

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = 
                    stove %>% 
                    factor %>% 
                    gsub(" ", "\n",.) %>% 
                    forcats::fct_relevel("three\nstone\nfire",
                                         "clay\nring",
                                         "ceramic\ncharcoal",
                                         "rocket\nelbow",
                                         "built-in\nplancha",
                                         "metal\ncharcoal",
                                         "fan\nrocket\nelbow",
                                         "gasifier",
                                         "wick\nkerosene",
                                         "pressure\nkerosene",
                                         "lpg"))
```

## add stove fuel info

```{r}
  emissions <-
    emissions %>%
    dplyr::left_join(samples %>%
                       dplyr::select(id, stove, fuel, stovecat, fuelcat), by = "id")
```

## select pollutants

```{r}
  gases <-
    emissions %>%
    dplyr::filter(grepl("^benzene|formaldehyde|styrene|acetaldehyde|isoprene", pol)) %>%
    dplyr::filter(metric == "energy_delivered_ef")
```

```{r}
  particles <-
    emissions %>%
    dplyr::filter(grepl("b.a.pyrene|dibenzo.*anthracene|cyclopenta.*pyrene|b.*anthracene|b...fluoranthene|indeno", pol)) %>%
    dplyr::filter(metric == "energy_delivered_ef") %>%
    dplyr::mutate(pol = gsub("indeno\\(1,2,3\\) cd pyrene", "indeno\\[1,2,3-cd\\]pyrene", pol),
                  pol = gsub("\\(ah\\)",  "\\[a,h\\]", pol),
                  pol = gsub("b\\[",  "benzo\\[", pol),
                  pol = gsub("b\\[",  "benzo\\[", pol))
```

# check for outliers

## gases

```{r, echo=FALSE, fig.width=10, fig.height=8, eval=FALSE}
  gases %>%
    dplyr::group_by(id) %>%
    dplyr::mutate(val = sum(val, na.rm = TRUE)) %>%
    ggplot(aes(x = id, y = val, color = fuel)) +
    geom_point() +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "top") +
    facet_wrap(~stove, scales = "free")
```

## particles

```{r, echo=FALSE, eval=FALSE,fig.width=10, fig.height=8}
  particles %>%
    dplyr::group_by(id) %>%
    dplyr::mutate(val = sum(val, na.rm = TRUE)) %>%
    ggplot(aes(x = id, y = val, color = fuel)) +
    geom_point() +
    theme_bw() +
    theme(text = element_text(size = 12),
          legend.position = "top") +
    facet_wrap(~stove, scales = "free")
```

## calculate stats

```{r}
  stats_gases <-
    gases %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

```{r}
  stats_particles <-
    particles %>%
    dplyr::group_by(id, stove, stovecat) %>%
    dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
    dplyr::group_by(stove, stovecat) %>%
    dplyr::summarise(min = min(val, na.rm = TRUE),
                     max = max(val, na.rm = TRUE)) %>%
    tidyr::gather("var", "val", min, max) %>%
    dplyr::mutate(sym = ifelse(var == "min", "[", "]"))
```

## calculate means by pollutant

```{r}
  gases <-
    gases %>%
    dplyr::group_by(pol, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::left_join(dplyr::select(pol_properties, pol, mw), by = "pol") %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_category = "gas phase emissions")
```

```{r}
  particles <-
    particles %>%
    dplyr::group_by(pol, stove, stovecat) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    dplyr::left_join(dplyr::select(pol_properties, pol, mw), by = "pol") %>%
    dplyr::ungroup() %>%
    dplyr::mutate(pol_category = "particle phase emissions")
```

# figures

```{r, echo=FALSE}
  p1 <-
    gases %>%
    dplyr::filter(grepl("traditional", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = forcats::fct_reorder(pol, mw, .desc = TRUE)), stat = "identity") +
      geom_text(data = stats_gases %>%
                dplyr::filter(grepl("traditional", stovecat)),
                aes(x = stove, y = val, label = sym), stroke = 2, size = 10, angle = 90, nudge_x = -0.05) +
      scale_fill_manual(values = c("gold3", "mediumseagreen", "palegoldenrod", "dodgerblue1", "dodgerblue4")) +
      scale_y_continuous(limits = c(0, 400)) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.title.y = element_text(size = 16),
            axis.text.y = element_text(size = 18),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            legend.position = "none") +
      guides(fill = guide_legend(title = NULL)) +
      facet_wrap(~stovecat, scales = "free") +
      ylab("mg emitted per MJ delivered")

  p2 <-
    gases %>%
    dplyr::filter(grepl("improved", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = forcats::fct_reorder(pol, mw, .desc = TRUE)), stat = "identity") +
      geom_text(data = stats_gases %>%
                dplyr::filter(grepl("improved", stovecat)),
                aes(x = stove, y = val, label = sym), stroke = 2, size = 10, angle = 90, nudge_x = -0.05) +
      theme_bw() +
      scale_fill_manual(values = c("gold3", "mediumseagreen", "palegoldenrod", "dodgerblue1", "dodgerblue4")) +
      theme(text = element_text(size = 20),
            axis.text.y = element_text(size = 18),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            legend.position = "none") +
      guides(fill = guide_legend(title = NULL)) +
      facet_wrap(~stovecat, scales = "free")
  
  p3 <-
    gases %>%
    dplyr::filter(grepl("liquid", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = forcats::fct_reorder(pol, mw, .desc = TRUE)), stat = "identity") +
      geom_text(data = stats_gases %>%
                dplyr::filter(grepl("liquid", stovecat)),
                aes(x = stove, y = val, label = sym), stroke = 2, size = 10, angle = 90, nudge_x = -0.05) +
      theme_bw() +
      scale_fill_manual(values = c("gold3", "mediumseagreen", "palegoldenrod", "dodgerblue1", "dodgerblue4")) +
      theme(text = element_text(size = 20),
            axis.text.y = element_text(size = 18),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            legend.position = "right",
            legend.text = element_text(size = 12)) +
      guides(fill = guide_legend(title = NULL)) +
      facet_grid(pol_category~stovecat, scales = "free")
```

```{r, echo=FALSE}
  p4 <-
    particles %>%
    dplyr::filter(grepl("traditional", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol, order = pol), stat = "identity") +
      geom_text(data = stats_particles %>%
                dplyr::filter(grepl("traditional", stovecat)),
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("plum4", "plum", "yellowgreen", "darkorchid", "lightsteelblue4", "lavender", "orange", "orangered4")) +
      scale_y_continuous(limits = c(0, 12)) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.title.y = element_text(size = 16),
            axis.title.x = element_blank(),
            axis.text.y = element_text(size = 18),
            strip.text.x = element_blank(),
            legend.position = "none") +
      guides(fill = guide_legend(title = NULL)) +
      facet_wrap(~stovecat, scales = "free") +
      ylab("mg emitted per MJ delivered")

  p5 <-
    particles %>%
    dplyr::filter(grepl("improved", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol, order = pol), stat = "identity") +
      geom_text(data = stats_particles %>%
                dplyr::filter(grepl("improved", stovecat)),
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("plum4", "plum", "yellowgreen", "darkorchid", "lightsteelblue4", "lavender", "orange", "orangered4")) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.title.x = element_blank(),
            axis.text.y = element_text(size = 18),
            axis.title.y = element_blank(),
            strip.text.x = element_blank(),
            legend.position = "none") +
      guides(fill = guide_legend(title = NULL)) +
      facet_wrap(~stovecat, scales = "free")
  
  p6 <-
    particles %>%
    dplyr::filter(grepl("liquid", stovecat)) %>%
    ggplot(aes(x = stove, y = val)) +
      geom_histogram(aes(fill = pol, order = pol), stat = "identity") +
      geom_text(data = stats_particles %>%
                dplyr::filter(grepl("liquid", stovecat)),
                aes(x = stove, y = val, label = sym), size = 10, angle = 90, nudge_x = -0.02) +
      scale_fill_manual(values = c("plum4", "plum", "yellowgreen", "darkorchid", "lightsteelblue4", "lavender", "orange", "orangered4")) +
      theme_bw() +
      theme(text = element_text(size = 20),
            axis.text.y = element_text(size = 18),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            strip.text.x = element_blank(),
            legend.position = "right",
            legend.text = element_text(size = 12)) +
      guides(fill = guide_legend(title = NULL)) +
      facet_grid(pol_category~stovecat, scales = "free")
```

```{r figure_1b, echo=FALSE, fig.width=16, fig.height=8}
 (p1 + p2 + p3) +
  p4 + p5 + p6 +  plot_layout(ncol = 3, widths = c(1, 1.5, 1))
```