---
title: "Database"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, patchwork, knitr, kableExtra, forcats,
                 RColorBrewer, stringi, pBrackets)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE)
```

```{r}
  emissions <- readRDS("../../../r_data/emissions_factors.RDS")
  samples <- readRDS("../../../r_data/samples.RDS")
```

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = 
                    stove %>% 
                    factor %>% 
                    forcats::fct_relevel("three-stone fire",
                                         "chulha",
                                         "rocket elbow",
                                         "built-in plancha",
                                         "fan rocket-elbow",
                                         "forced-draft gasifier",
                                         "ceramic charcoal",
                                         "metal charcoal",
                                         "wick kerosene",
                                         "pressure kerosene",
                                         "lpg") %>%
                    forcats::fct_recode("Three-stone fire" = "three-stone fire",
                                         "Mud chulha" = "chulha",
                                         "Rocket elbow" = "rocket elbow",
                                         "Built-in plancha" = "built-in plancha",
                                         "Fan rocket elbow" = "fan rocket-elbow",
                                         "Gasifier" = "forced-draft gasifier",
                                         "Ceramic jiko" = "ceramic charcoal",
                                          "Metal jiko" = "metal charcoal",
                                          "Wick kerosene" = "wick kerosene",
                                         "Pressure kerosene" = "pressure kerosene",
                                          "LPG" = "lpg"),
                  fuel = 
                    fuel %>%
                    factor %>%
                    forcats::fct_recode("Douglas fir" = "douglas fir",
                                         "Eucalyptus" = "eucalyptus",
                                         "Oak" = "oak",
                                         "Coconut briquettes" = "coconut charcoal",
                                         "Hardwood lumps (Sm)" = "lump hardwood (sm.)",
                                         "Hardwood lumps (Med)" = "lump hardwood (med.)",
                                         "Eucalyptus pellets" = "eucalyptus pellets",
                                         "Lodgepole pine pellets" = "west slope pellets",
                                         "Kerosene" = "kerosene",
                                         "LPG" = "lpg") %>%
                    forcats::fct_relevel("Douglas fir",
                                         "Eucalyptus",
                                         "Oak",
                                         "Coconut briquettes",
                                         "Hardwood lumps (Sm)",
                                         "Hardwood lumps (Med)",
                                         "Eucalyptus pellets",
                                         "Lodgepole pine pellets",
                                         "Kerosene",
                                         "LPG"))
```

```{r, echo=FALSE}
  energy_delivered <-
    emissions %>%
    dplyr::filter(grepl("energy_delivered_ef", metric), !grepl("unc", pol), is.na(pol)) %>%
    dplyr::select(-qc, -units) %>%
    tidyr::spread("metric", "val") %>%
    dplyr::full_join(samples %>%
                        dplyr::select(id, stove, fuel), by = "id") %>%
    dplyr::select(id, stove, fuel, pol, energy_delivered_ef, lod, bg) %>%
    dplyr::mutate(id = as.factor(id)) %>%
    dplyr::rename("val" = "energy_delivered_ef") %>%
    dplyr::mutate(pol = ifelse(grepl("pm_mass", pol), "PM2.5 mass", pol),
                  pol = ifelse(grepl("^co2$", pol), "carbon dioxide", pol),
                  pol = ifelse(grepl("^co$", pol), "carbon monoxide", pol),
                  pol = ifelse(grepl("^ch4$", pol), "methane", pol),
                  pol = ifelse(grepl("ultrafines", pol), "ultrafine particles", pol),
                  pol = ifelse(grepl("^om$", pol), "organic matter", pol),
                  pol = ifelse(grepl("^oc$", pol), "organic carbon", pol),
                  pol = ifelse(grepl("^ec$", pol), "elemental carbon", pol),
                  pol = ifelse(grepl("pinene", pol), "alpha-pinene", pol),
                  pol = ifelse(grepl("2_methyl_2_butene", pol), "2-methyl-2-butene", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([a-z])", "\\1-\\3", pol),
                  pol = gsub("([a-z])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("(m)(_)(p)", "\\1,\\3", pol),
                  pol = gsub("([a-z])(_)([a-z])", "\\1-\\3", pol)) %>%
    dplyr::arrange(id)

  readr::write_csv(energy_delivered, "database/per_energy_delivered.csv")
```

```{r, echo=FALSE}
  mass_fuel <-
    emissions %>%
    dplyr::filter(grepl("mass_fuel_ef", metric), !grepl("unc", pol), is.na(pol)) %>%
    dplyr::select(-qc, -units) %>%
    tidyr::spread("metric", "val") %>%
    dplyr::full_join(samples %>%
                        dplyr::select(id, stove, fuel), by = "id") %>%
    dplyr::select(id, stove, fuel, pol, mass_fuel_ef, lod, bg) %>%
    dplyr::mutate(id = as.factor(id)) %>%
    dplyr::rename("val" = "mass_fuel_ef") %>%
    dplyr::mutate(pol = ifelse(grepl("pm_mass", pol), "PM2.5 mass", pol),
                  pol = ifelse(grepl("^co2$", pol), "carbon dioxide", pol),
                  pol = ifelse(grepl("^co$", pol), "carbon monoxide", pol),
                  pol = ifelse(grepl("^ch4$", pol), "methane", pol),
                  pol = ifelse(grepl("ultrafines", pol), "ultrafine particles", pol),
                  pol = ifelse(grepl("^om$", pol), "organic matter", pol),
                  pol = ifelse(grepl("^oc$", pol), "organic carbon", pol),
                  pol = ifelse(grepl("^ec$", pol), "elemental carbon", pol),
                  pol = ifelse(grepl("pinene", pol), "alpha-pinene", pol),
                  pol = ifelse(grepl("2_methyl_2_butene", pol), "2-methyl-2-butene", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([a-z])", "\\1-\\3", pol),
                  pol = gsub("([a-z])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("(m)(_)(p)", "\\1,\\3", pol),
                  pol = gsub("([a-z])(_)([a-z])", "\\1-\\3", pol)) %>%
    dplyr::arrange(id)

  readr::write_csv(mass_fuel, "database/per_mass_fuel.csv")
```

```{r, echo=FALSE}
  energy_fuel <-
    emissions %>%
    dplyr::filter(grepl("energy_fuel_ef", metric), !grepl("unc", pol), is.na(pol)) %>%
    dplyr::select(-qc, -units) %>%
    tidyr::spread("metric", "val") %>%
    dplyr::full_join(samples %>%
                        dplyr::select(id, stove, fuel), by = "id") %>%
    dplyr::select(id, stove, fuel, pol, energy_fuel_ef, lod, bg) %>%
    dplyr::mutate(id = as.factor(id)) %>%
    dplyr::rename("val" = "energy_fuel_ef") %>%
    dplyr::mutate(pol = ifelse(grepl("pm_mass", pol), "PM2.5 mass", pol),
                  pol = ifelse(grepl("^co2$", pol), "carbon dioxide", pol),
                  pol = ifelse(grepl("^co$", pol), "carbon monoxide", pol),
                  pol = ifelse(grepl("^ch4$", pol), "methane", pol),
                  pol = ifelse(grepl("ultrafines", pol), "ultrafine particles", pol),
                  pol = ifelse(grepl("^om$", pol), "organic matter", pol),
                  pol = ifelse(grepl("^oc$", pol), "organic carbon", pol),
                  pol = ifelse(grepl("^ec$", pol), "elemental carbon", pol),
                  pol = ifelse(grepl("pinene", pol), "alpha-pinene", pol),
                  pol = ifelse(grepl("2_methyl_2_butene", pol), "2-methyl-2-butene", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([a-z])", "\\1-\\3", pol),
                  pol = gsub("([a-z])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("(m)(_)(p)", "\\1,\\3", pol),
                  pol = gsub("([a-z])(_)([a-z])", "\\1-\\3", pol)) %>%
    dplyr::arrange(id)

  readr::write_csv(energy_fuel, "database/per_energy_fuel.csv")
```

```{r, echo=FALSE}
  emissions_rate <-
    emissions %>%
    dplyr::filter(grepl("emissions_rate", metric), !grepl("unc", pol), is.na(pol)) %>%
    dplyr::select(-qc, -units) %>%
    tidyr::spread("metric", "val") %>%
    dplyr::full_join(samples %>%
                        dplyr::select(id, stove, fuel), by = "id") %>%
    dplyr::select(id, stove, fuel, pol, emissions_rate, lod, bg) %>%
    dplyr::mutate(id = as.factor(id)) %>%
    dplyr::rename("val" = "emissions_rate") %>%
    dplyr::mutate(pol = ifelse(grepl("pm_mass", pol), "PM2.5 mass", pol),
                  pol = ifelse(grepl("^co2$", pol), "carbon dioxide", pol),
                  pol = ifelse(grepl("^co$", pol), "carbon monoxide", pol),
                  pol = ifelse(grepl("^ch4$", pol), "methane", pol),
                  pol = ifelse(grepl("ultrafines", pol), "ultrafine particles", pol),
                  pol = ifelse(grepl("^om$", pol), "organic matter", pol),
                  pol = ifelse(grepl("^oc$", pol), "organic carbon", pol),
                  pol = ifelse(grepl("^ec$", pol), "elemental carbon", pol),
                  pol = ifelse(grepl("pinene", pol), "alpha-pinene", pol),
                  pol = ifelse(grepl("2_methyl_2_butene", pol), "2-methyl-2-butene", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([a-z])", "\\1-\\3", pol),
                  pol = gsub("([a-z])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("(m)(_)(p)", "\\1,\\3", pol),
                  pol = gsub("([a-z])(_)([a-z])", "\\1-\\3", pol)) %>%
    dplyr::arrange(id)

  readr::write_csv(emissions_rate, "database/per_time.csv")
```