---
title: "tables"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
  word_document:
    toc: yes
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, pals, devtools, kableExtra, xtable)
  #devtools::install_github("thomasp85/patchwork")
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# mce & firepower table

## load data

```{r}
  mce <- readRDS("../../../r_data/mce_avg.RDS")
  samples <- readRDS("../../../r_data/samples.RDS")
  fuel <- readRDS("../../../r_data/fuel_merged.RDS")
```

## add stove-fuel info, fuel info and pol properties

```{r}
  mce <-
    mce %>%
    dplyr::inner_join(samples %>%
                        dplyr::select(id, stove, fuel, stovecat, fuelcat), by = "id") %>%
    dplyr::inner_join(fuel, by = c("id", "fuel"))
```

## calculate firepower

```{r}
  mce_fp <-
    mce %>%
    dplyr::mutate(fp = (mass_fuel_comb * 1e-3) / (dur * 60) * lhv)
```

## aggregate data

```{r}
  mce_fp %>%
    dplyr::group_by(stove) %>%
    dplyr::summarise(mce = mean(mce, na.rm = TRUE),
                     fp = mean(fp, na.rm = TRUE)) %>%
    knitr::kable("markdown", digits = 3, align = 'c')
```

# emissions table

## load data

```{r}
  emissions <- readRDS("../../../r_data/emissions_factors.RDS")
```

## add stove-fuel info, fuel info and pol properties

```{r}

    emissions %>%
      dplyr::filter(metric == "energy_delivered_ef") %>%
      dplyr::inner_join(samples %>%
                          dplyr::select(id, stove, fuel, stovecat, fuelcat), by = "id") %>%
      dplyr::filter(stovecat == "liquid-fuel stoves") %>%
      dplyr::select(id, pol, val) %>%
      tidyr::spread(id, val) %>%
    knitr::kable("markdown", digits = 3, align = 'c')
```

## table

```{r results = "asis"}
  # print(xtable::xtable(wood),
  #       type = "html")
```
