---
title: "figure 1: particle emissions"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, wordcloud2, webshot, htmlwidgets)
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# figure 1

## tidy data

load data

```{r}
  emissions <- readRDS("../../../r_data/emissions_factors.RDS")
  samples <- readRDS("../../../r_data/samples.RDS")
```

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = 
                    stove %>% 
                    factor %>% 
                    forcats::fct_relevel("three-stone fire",
                                         "chulha",
                                         "rocket elbow",
                                         "built-in plancha",
                                         "fan rocket-elbow",
                                         "forced-draft gasifier",
                                         "ceramic charcoal",
                                         "metal charcoal",
                                         "wick kerosene",
                                         "pressure kerosene",
                                         "lpg"))
```

## add stove fuel info

```{r}
  emissions <-
    emissions %>%
    dplyr::left_join(samples %>%
                       dplyr::select(id, stove, fuel, stovecat, fuelcat), by = "id")
```

## filter out values below background

```{r}
  three_stone <-
    emissions %>%
    dplyr::filter(stove == "three-stone fire", !grepl("unc", pol), pol != "organic carbon") %>%
    dplyr::filter(metric == "energy_delivered_ef") %>%
    dplyr::group_by(pol) %>%
    dplyr::summarise(val = 0.1)  %>%
    dplyr::filter(!grepl("organic matter", pol)) %>%
    dplyr::mutate(pol = ifelse(pol == "pm_mass", "fine particulate matter", pol),
                  pol = ifelse(grepl("^co2$", pol), "carbon dioxide", pol),
                  pol = ifelse(grepl("^co$", pol), "carbon monoxide", pol),
                  pol = ifelse(grepl("^ch4$", pol), "methane", pol),
                  pol = ifelse(grepl("ultrafines", pol), "ultrafine particles", pol),
                  pol = ifelse(grepl("^om$", pol), "organic matter", pol),
                  pol = ifelse(grepl("^oc$", pol), "organic carbon", pol),
                  pol = ifelse(grepl("^ec$", pol), "elemental carbon", pol),
                  pol = ifelse(grepl("pinene", pol), "alpha-pinene", pol),
                  pol = ifelse(grepl("2_methyl_2_butene", pol), "2-methyl-2-butene", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("([0-9])(_)([a-z])", "\\1-\\3", pol),
                  pol = gsub("([a-z])(_)([0-9])", "\\1,\\3", pol),
                  pol = gsub("(m)(_)(p)", "\\1,\\3", pol),
                  pol = gsub("([a-z])(_)([a-z])", "\\1-\\3", pol))
```

# word cloud

```{r, fig.width=10, fig.height=10}
  wordcloud2(three_stone, figPath = "cloud.jpg", color = "black", size = 0.1)
```

