---
title: "NIH Aim 1 Data Analysis"
author: "Nick Good, Kristen Fedak, and Kelsey Bilsback"
date: "April 21, 2017"
output:
  ioslides_presentation: default
  beamer_presentation: default
---

 <style> #margins > p {margin-top: -25px; margin-left: -125px;} </style>

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

  library(tidyverse)
  library(forcats)
```

```{r setup}
  load("../r_files/emission_factors.Rda")
  load("../r_files/samples.Rda")
  source("../r_scripts/R_functions.R")
  
  emission_factors <- dplyr::left_join(emission_factors, 
                                       dplyr::select(samples, id, stove, fuel,
                                                              fuelcat, stovecat),
                                       by = "id")
  emission_factors <- dplyr::mutate(emission_factors, 
                                    mass_ef_comb = 
                                      ifelse(is.na(mass_ef),
                                             mass_c_ef, mass_ef)) %>%
                      dplyr::filter(mass_ef_comb > 0)

  emission_factors <- dplyr::mutate(emission_factors,
                                    pol = forcats::fct_recode(pol, "pm" = "grav"),
                                    inst = forcats::fct_recode(inst, "pm" = "grav"),
                                    inst = forcats::fct_recode(inst, "vocs" = "voc"),
                                    inst = forcats::fct_recode(inst, "carbonyls" = "carbs")) %>%
                      dplyr::filter(!grepl("Mimi Moto|Prototype", stove))

  emission_factors <- dplyr::mutate(emission_factors, 
                                    mass_ef_comb = 
                                      ifelse(is.na(mass_ef),
                                             mass_c_ef, mass_ef)) %>%
                      dplyr::mutate(energy_ef_comb =
                                      ifelse(is.na(energy_ef), energy_c_ef,
                                             energy_ef))
```

## Missing Test Overview {#margins}

```{r missing_wood_tests, fig.width=9, fig.height=6}
  summarise_reps(dplyr::filter(emission_factors, fuelcat == "wood"), "inst")
```

## Missing Test Overview {#margins}

```{r missing_charcoal_tests, fig.width=9, fig.height=6}
  summarise_reps(dplyr::filter(emission_factors, fuelcat == "charcoal"), "inst")
```

## Missing Test Overview {#margins}

```{r missing_gasifier_advanced_tests, fig.width=9, fig.height=6}
  summarise_reps(dplyr::filter(emission_factors, grepl("pellets|advanced",fuelcat)), "inst")
```

## Emissions Overview {#margins}

## PM vs. CO {#margins}

## Correlation Analysis {#margins}

