---
title: "Combine all pollutant data and calculate additional emissions metrics"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse)
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

## load files

pollutant data

```{r}
  samples <- readRDS("../../r_data/samples.RDS")
  ecoc <- readRDS("../../r_data/ecoc_merged.RDS")
  pm <- readRDS("../../r_data/pm_merged.RDS")
  carbonyls <- readRDS("../../r_data/carbonyls_merged.RDS")
  carbohydrates <- readRDS("../../r_data/carbohydrates_merged.RDS")
  ions <- readRDS("../../r_data/ions_merged.RDS")
  vocs <- readRDS("../../r_data/vocs_merged.RDS")
  pahs <- readRDS("../../r_data/pah_merged.RDS")
  ultrafines <- readRDS("../../r_data/ultrafines_merged.RDS")
```

constants

```{r}
  hood_flow <- readRDS("../../r_data/hood_flow.RDS")
  mw_c <- readRDS("../../r_data/mw_c.RDS")
  pol_properties <- readRDS("../../r_data/pol_properties.RDS")
```

# combine pollutants

```{r}
  emissions <-
    ecoc %>%
    dplyr::bind_rows(pm, carbonyls, carbohydrates, ions, vocs, pahs)
    
```

# calculate additional metrics

```{r}
  emissions <- 
    emissions %>%
    dplyr::rename("conc" = "val") %>%
    dplyr::left_join(pol_properties, by = "pol") %>%
    dplyr::mutate(mass_emitted = conc * hood_flow * dur,
                  mass_carbon = mass_emitted * (num_c * mw_c / mw)) %>%
    dplyr::select(id, pol_category, pol, conc, mass_emitted, mass_carbon, qc) %>%
    tidyr::gather("metric", "val", 4:6) %>%
    dplyr::mutate(units = ifelse(metric == "conc", "micrograms per cm cubed", "micrograms")) %>%
    dplyr::filter(!is.na(val))
```

# add ultrafines

```{r}
  emissions <-
    emissions %>%
    dplyr::bind_rows(ultrafines %>%
                      dplyr::mutate(metric = "num_conc",
                                    units = "number per cm cubed")) %>%
    dplyr::filter(!is.na(val), !grepl("27|28|29|30", id))
```

# save

```{r}
  saveRDS(emissions, file = "../../r_data/emissions.RDS")
```

# exploratory analysis

## plot: gas composition

```{r, echo=FALSE, fig.width=10}
  emissions %>%
  dplyr::filter(metric == "mass_emitted",
                grepl("carbonyls|pahs|vocs", pol_category)) %>%
  dplyr::mutate(val = val / 10e3) %>%
  dplyr::group_by(id, pol_category) %>%
  dplyr::summarise(val = sum(val, na.rm = TRUE)) %>%
  dplyr::left_join(dplyr::select(samples, id, stove, fuel), by = "id") %>%
  dplyr::group_by(stove, fuel, pol_category) %>%
  dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
  ggplot(aes(x = stove, y = val, fill = fuel)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    coord_flip() +
    theme_bw() +
    theme(text = element_text(size = 16),
          legend.position = "top") +
    facet_wrap(~pol_category, scales = "free") +
    ylab("mass emitted (miligrams)") +
    xlab("")
```

## plot: particle composition

```{r, echo=FALSE, fig.width=12, fig.height=10}
  emissions %>%
  dplyr::filter(metric == "mass_emitted",
                grepl("ions|ecoc", pol_category)) %>%
  dplyr::mutate(val = val / 10e3) %>%
  dplyr::left_join(dplyr::select(samples, id, stove, fuel), by = "id") %>%
  dplyr::group_by(stove, fuel, pol) %>%
  dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
  ggplot(aes(x = stove, y = val, fill = fuel)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    coord_flip() +
    theme_bw() +
    theme(text = element_text(size = 16),
          legend.position = "top") +
    facet_wrap(~pol, scales = "free") +
    ylab("mass emitted (miligrams)") +
    xlab("")
```